//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreatModelForge.Analysis.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreatModelForge.Analysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up the localized DefaultToolInformationUri resource string.
        /// </summary>
        internal static string DefaultToolInformationUri {
            get {
                return ResourceManager.GetString("DefaultToolInformationUri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized DefaultToolOrganization resource string.
        /// </summary>
        internal static string DefaultToolOrganization {
            get {
                return ResourceManager.GetString("DefaultToolOrganization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized EntityRequiresDrawingSurfaceFormatString resource string.
        /// </summary>
        internal static string EntityRequiresDrawingSurfaceFormatString {
            get {
                return ResourceManager.GetString("EntityRequiresDrawingSurfaceFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) ID={2}.
        /// </summary>
        internal static string NamedEntityWithKnownTypeFormatString {
            get {
                return ResourceManager.GetString("NamedEntityWithKnownTypeFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of unknown type and ID={1}.
        /// </summary>
        internal static string NamedEntityWithUnknownTypeFormatString {
            get {
                return ResourceManager.GetString("NamedEntityWithUnknownTypeFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unnamed entity with ID={0}.
        /// </summary>
        internal static string UnnamedEntityWithIDFormatString {
            get {
                return ResourceManager.GetString("UnnamedEntityWithIDFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unnamed entity of type {0} and ID={1}.
        /// </summary>
        internal static string UnnamedEntityWithKnownTypeFormatString {
            get {
                return ResourceManager.GetString("UnnamedEntityWithKnownTypeFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized UnresolvedDrawingSurfaceFormatString resource string.
        /// </summary>
        internal static string UnresolvedDrawingSurfaceFormatString {
            get {
                return ResourceManager.GetString("UnresolvedDrawingSurfaceFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized UnresolvedEntityFormatString resource string.
        /// </summary>
        internal static string UnresolvedEntityFormatString {
            get {
                return ResourceManager.GetString("UnresolvedEntityFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized UnresolvedRuleFormatString resource string.
        /// </summary>
        internal static string UnresolvedRuleFormatString {
            get {
                return ResourceManager.GetString("UnresolvedRuleFormatString", resourceCulture);
            }
        }
    }
}
