namespace ThreatModelForge.Formats
{
    using System;
    using ThreatModelForge.KnowledgeBase;

    /// <summary>
    /// Maps threat lifecycle state between the <c>tmforge-json</c> wire vocabulary
    /// (<c>Open</c> / <c>NeedsInvestigation</c> / <c>Mitigated</c> / <c>Accepted</c>) and the
    /// <see cref="ThreatState"/> register enum. <c>Open</c> and <c>Accepted</c> are retained as
    /// back-compatible aliases for the auto-generated and not-applicable states.
    /// </summary>
    public static class ThreatStateWire
    {
        /// <summary>The register-key prefix that marks a manually-authored threat.</summary>
        public const string ManualKeyPrefix = "manual:";

        /// <summary>Parses a wire state string into a <see cref="ThreatState"/>.</summary>
        /// <param name="state">The wire state string.</param>
        /// <returns>The register state (defaults to <see cref="ThreatState.AutoGenerated"/>).</returns>
        public static ThreatState Parse(string? state)
        {
            if (string.Equals(state, "Accepted", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(state, "NotApplicable", StringComparison.OrdinalIgnoreCase))
            {
                return ThreatState.NotApplicable;
            }

            if (string.Equals(state, "Mitigated", StringComparison.OrdinalIgnoreCase))
            {
                return ThreatState.Mitigated;
            }

            if (string.Equals(state, "NeedsInvestigation", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(state, "NeedsMitigation", StringComparison.OrdinalIgnoreCase))
            {
                return ThreatState.NeedsInvestigation;
            }

            return ThreatState.AutoGenerated;
        }

        /// <summary>Formats a <see cref="ThreatState"/> as its canonical wire state string.</summary>
        /// <param name="state">The register state.</param>
        /// <returns>The canonical wire state string.</returns>
        public static string ToWire(ThreatState state)
        {
            switch (state)
            {
                case ThreatState.NotApplicable:
                    return "Accepted";
                case ThreatState.Mitigated:
                    return "Mitigated";
                case ThreatState.NeedsInvestigation:
                    return "NeedsInvestigation";
                default:
                    return "Open";
            }
        }

        /// <summary>Canonicalizes a wire state string, resolving aliases.</summary>
        /// <param name="state">The wire state string.</param>
        /// <returns>The canonical wire state string.</returns>
        public static string Canonical(string? state) => ToWire(Parse(state));

        /// <summary>Determines whether a register key denotes a manually-authored threat.</summary>
        /// <param name="key">The register key or interaction key.</param>
        /// <returns><see langword="true"/> when the key marks a manual threat.</returns>
        public static bool IsManualKey(string? key)
            => key != null && key.StartsWith(ManualKeyPrefix, StringComparison.OrdinalIgnoreCase);
    }
}
