namespace ThreatModelForge.Engine
{
    /// <summary>A source diagram rendered without editing its geometry or trust boundaries.</summary>
    public sealed class DiagramPreviewDto
    {
        /// <summary>Gets the stable page identifier.</summary>
        public string Id { get; init; } = string.Empty;

        /// <summary>Gets the page title.</summary>
        public string Name { get; init; } = string.Empty;

        /// <summary>Gets the standalone SVG generated by the engine.</summary>
        public string Svg { get; init; } = string.Empty;
    }
}
