namespace ThreatModelForge.Reporting
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Xml.Linq;
    using ThreatModelForge.KnowledgeBase;
    using ThreatModelForge.Model;

    /// <summary>
    /// Produces a self-contained HTML report for a threat model. All model-supplied text is
    /// emitted through <see cref="XElement"/>, which escapes it, so a report cannot be used to
    /// inject markup or script.
    /// </summary>
    public sealed class HtmlReportWriter
    {
        private const string NonBreakingSpace = "\u00A0";

        private const string Css =
            "body { font-family: 'Segoe UI', Helvetica, sans-serif; margin: 2rem; color: #111; }"
            + " h1 { color: #1a3a6b; } h2 { color: #1a3a6b; border-bottom: 1px solid #ccd; padding-bottom: 0.2rem; margin-top: 2rem; }"
            + " .meta p { margin: 0.15rem 0; } .summary span { margin-right: 1.5rem; font-weight: bold; }"
            + " .diagram { border: 1px solid #ccd; padding: 0.5rem; margin: 0.5rem 0; overflow: auto; background: #fafbff; }"
            + " table.threats { border-collapse: collapse; width: 100%; margin-top: 0.5rem; }"
            + " table.threats th, table.threats td { border: 1px solid #ccd; padding: 0.4rem 0.6rem; text-align: left; vertical-align: top; font-size: 0.9rem; }"
            + " table.threats th { background: #eef2ff; } .state-mitigated { color: #187a18; } .state-open { color: #b00000; }";

        /// <summary>
        /// Writes an HTML report for the given model.
        /// </summary>
        /// <param name="model">The threat model.</param>
        /// <returns>The HTML document text.</returns>
        public string Write(ThreatModel model)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            XElement body = new XElement("body");
            body.Add(new XElement("h1", "Threat Modeling Report"));
            body.Add(new XElement("p", new XElement("em", "Created on " + DateTime.Now.ToString("f", CultureInfo.CurrentCulture))));

            AddMetadata(body, model.MetaInformation);
            AddSummary(body, model);
            AddNotes(body, model.Notes);

            DiagramSvgRenderer renderer = new DiagramSvgRenderer();
            for (int i = 0; i < model.DrawingSurfaceList.Count; i++)
            {
                AddDiagramSection(body, model.DrawingSurfaceList[i], model, renderer);
            }

            XElement html = new XElement("html", new XAttribute("lang", "en-US"), BuildHead(), body);
            return "<!DOCTYPE html>" + Environment.NewLine + html;
        }

        private static XElement BuildHead()
        {
            return new XElement(
                "head",
                new XElement("meta", new XAttribute("charset", "utf-8")),
                new XElement("title", "Threat Modeling Report"),
                new XElement("style", new XAttribute("type", "text/css"), Css));
        }

        private static void AddMetadata(XElement body, MetaInformation? meta)
        {
            XElement section = new XElement("div", new XAttribute("class", "meta"));
            section.Add(MetadataLine("Threat Model Name", meta?.ThreatModelName));
            section.Add(MetadataLine("Owner", meta?.Owner));
            section.Add(MetadataLine("Reviewer", meta?.Reviewer));
            section.Add(MetadataLine("Contributors", meta?.Contributors));
            section.Add(MetadataLine("Description", meta?.HighLevelSystemDescription));
            section.Add(MetadataLine("Assumptions", meta?.Assumptions));
            section.Add(MetadataLine("External Dependencies", meta?.ExternalDependencies));
            body.Add(section);
        }

        private static XElement MetadataLine(string label, string? value)
        {
            return new XElement("p", new XElement("strong", label + ": "), value ?? string.Empty);
        }

        private static void AddSummary(XElement body, ThreatModel model)
        {
            IList<Threat> threats = model.AllThreatsDictionary.Values.ToList();
            body.Add(new XElement("h2", "Summary"));

            XElement summary = new XElement("p", new XAttribute("class", "summary"));
            summary.Add(new XElement("span", "Total threats: " + threats.Count.ToString(CultureInfo.InvariantCulture)));

            foreach (ThreatState state in new[] { ThreatState.AutoGenerated, ThreatState.NeedsInvestigation, ThreatState.NotApplicable, ThreatState.Mitigated })
            {
                int count = threats.Count(t => t.State == state);
                summary.Add(new XElement("span", StateText(state) + ": " + count.ToString(CultureInfo.InvariantCulture)));
            }

            body.Add(summary);
        }

        private static void AddNotes(XElement body, IEnumerable<Note> notes)
        {
            List<Note> ordered = notes.OrderBy(n => n.Id).ToList();
            if (ordered.Count == 0)
            {
                return;
            }

            body.Add(new XElement("h2", "Notes"));
            XElement list = new XElement("ul");
            foreach (Note note in ordered)
            {
                list.Add(new XElement("li", note.Message ?? string.Empty));
            }

            body.Add(list);
        }

        private static void AddDiagramSection(XElement body, DrawingSurfaceModel diagram, ThreatModel model, DiagramSvgRenderer renderer)
        {
            body.Add(new XElement("h2", DiagramTitle(diagram)));
            body.Add(new XElement("div", new XAttribute("class", "diagram"), renderer.Render(diagram)));

            List<Threat> threats = model.AllThreatsDictionary.Values
                .Where(t => t.DrawingSurfaceGuid == diagram.Guid)
                .OrderBy(t => t.TypeId, StringComparer.Ordinal)
                .ToList();

            if (threats.Count == 0)
            {
                body.Add(new XElement("p", new XElement("em", "No threats recorded for this diagram.")));
                return;
            }

            XElement table = new XElement("table", new XAttribute("class", "threats"));
            table.Add(new XElement(
                "thead",
                new XElement(
                    "tr",
                    HeaderCell("#"),
                    HeaderCell("Title"),
                    HeaderCell("Category"),
                    HeaderCell("State"),
                    HeaderCell("Priority"),
                    HeaderCell("Description"),
                    HeaderCell("Mitigation"))));

            XElement tableBody = new XElement("tbody");
            int number = 0;
            foreach (Threat threat in threats)
            {
                tableBody.Add(BuildThreatRow(++number, threat));
            }

            table.Add(tableBody);
            body.Add(table);
        }

        private static XElement BuildThreatRow(int number, Threat threat)
        {
            string title = FirstNonEmpty(threat.Title, threat.TypeId, "Threat");
            string category = FirstNonEmpty(threat.UserThreatCategory);
            string description = FirstNonEmpty(threat.UserThreatDescription, threat.UserThreatShortDescription);
            string mitigation = FirstNonEmpty(threat.StateInformation, "(no mitigation provided)");
            bool mitigated = threat.State == ThreatState.Mitigated;

            return new XElement(
                "tr",
                Cell(number.ToString(CultureInfo.InvariantCulture)),
                Cell(title),
                Cell(category),
                new XElement("td", new XAttribute("class", mitigated ? "state-mitigated" : "state-open"), StateText(threat.State)),
                Cell(threat.Priority),
                Cell(description),
                Cell(mitigation));
        }

        private static string DiagramTitle(DrawingSurfaceModel diagram)
        {
            return string.IsNullOrEmpty(diagram.Header) ? "Diagram" : diagram.Header!;
        }

        private static string StateText(ThreatState state)
        {
            switch (state)
            {
                case ThreatState.AutoGenerated:
                    return "Not Started";
                case ThreatState.NotApplicable:
                    return "Not Applicable";
                case ThreatState.NeedsInvestigation:
                    return "Needs Investigation";
                case ThreatState.Mitigated:
                    return "Mitigation Implemented";
                default:
                    return state.ToString();
            }
        }

        private static string FirstNonEmpty(params string?[] values)
        {
            foreach (string? value in values.Where(value => !string.IsNullOrEmpty(value)))
            {
                return value!;
            }

            return string.Empty;
        }

        private static XElement HeaderCell(string text)
        {
            return new XElement("th", text);
        }

        private static XElement Cell(string? text)
        {
            return new XElement("td", string.IsNullOrEmpty(text) ? NonBreakingSpace : text!);
        }
    }
}
