namespace ThreatModelForge.Reporting
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Text;
    using ThreatModelForge.KnowledgeBase;
    using ThreatModelForge.Model;
    using ThreatModelForge.Model.Abstracts;

    /// <summary>Writes a deterministic Markdown view of a model and its complete threat register.</summary>
    public sealed class MarkdownReportWriter
    {
        /// <summary>Writes a report without evaluating rules or modifying the model.</summary>
        /// <param name="model">The model with its already-materialized threat register.</param>
        /// <param name="staleThreatIds">Register keys classified as stale by the caller, if known.</param>
        /// <returns>Markdown text with LF line endings and no generated timestamp.</returns>
        public string Write(ThreatModel model, IReadOnlyCollection<string>? staleThreatIds = null)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            StringBuilder output = new StringBuilder();
            HashSet<string> stale = new HashSet<string>(staleThreatIds ?? Array.Empty<string>(), StringComparer.OrdinalIgnoreCase);
            Dictionary<Guid, string> names = new Dictionary<Guid, string>();
            output.Append("# ").Append(Text(First(model.MetaInformation?.ThreatModelName, "Threat Modeling Report"))).Append("\n\n");
            Field(output, "Description", model.MetaInformation?.HighLevelSystemDescription);
            Field(output, "Owner", model.MetaInformation?.Owner);
            Field(output, "Reviewer", model.MetaInformation?.Reviewer);
            Field(output, "Contributors", model.MetaInformation?.Contributors);
            Field(output, "Assumptions", model.MetaInformation?.Assumptions);
            Field(output, "External dependencies", model.MetaInformation?.ExternalDependencies);

            output.Append("\n## Summary\n\n| Status | Threats |\n| --- | ---: |\n");
            foreach (ThreatState state in new[] { ThreatState.AutoGenerated, ThreatState.NeedsInvestigation, ThreatState.Mitigated, ThreatState.NotApplicable })
            {
                output.Append("| ").Append(State(state)).Append(" | ")
                    .Append(model.AllThreatsDictionary.Values.Count(threat => threat.State == state).ToString(CultureInfo.InvariantCulture)).Append(" |\n");
            }

            output.Append("| Total | ").Append(model.AllThreatsDictionary.Count.ToString(CultureInfo.InvariantCulture)).Append(" |\n");
            if (model.Notes.Count > 0)
            {
                output.Append("\n## Notes\n\n");
                foreach (Note note in model.Notes.OrderBy(note => note.Id).ThenBy(note => note.Message, StringComparer.Ordinal))
                {
                    output.Append("- ").Append(Text(note.Message)).Append('\n');
                }
            }

            foreach (DrawingSurfaceModel diagram in model.DrawingSurfaceList)
            {
                foreach (Entity entity in diagram.Borders.Values.Concat(diagram.Lines.Values).OfType<Entity>())
                {
                    names[entity.Guid] = Name(entity);
                }
            }

            foreach (DrawingSurfaceModel diagram in model.DrawingSurfaceList)
            {
                output.Append("\n## Diagram: ").Append(Text(First(diagram.Header, "Diagram"))).Append("\n\n");
                Field(output, "Diagram ID", diagram.Guid.ToString("D"));
                output.Append("\n| Object ID | Name | Type |\n| --- | --- | --- |\n");
                foreach (DrawingElement element in diagram.Borders.Values.OfType<DrawingElement>().OrderBy(element => element.Guid))
                {
                    output.Append("| ").Append(element.Guid.ToString("D")).Append(" | ").Append(Text(Name(element)))
                        .Append(" | ").Append(Text(First(element.GenericTypeId, element.GetType().Name))).Append(" |\n");
                }

                output.Append("\n| Flow ID | Name | Source | Target |\n| --- | --- | --- | --- |\n");
                foreach (Connector flow in diagram.Lines.Values.OfType<Connector>().OrderBy(flow => flow.Guid))
                {
                    output.Append("| ").Append(flow.Guid.ToString("D")).Append(" | ").Append(Text(Name(flow)))
                        .Append(" | ").Append(Text(Resolve(flow.SourceGuid, names)))
                        .Append(" | ").Append(Text(Resolve(flow.TargetGuid, names))).Append(" |\n");
                }
            }

            output.Append("\n## Threat register\n\n");
            if (model.AllThreatsDictionary.Count == 0)
            {
                output.Append("No threats recorded.\n");
            }

            foreach (KeyValuePair<string, Threat> entry in model.AllThreatsDictionary.OrderBy(entry => entry.Key, StringComparer.Ordinal))
            {
                Threat threat = entry.Value;
                bool manual = string.IsNullOrWhiteSpace(threat.TypeId) || ManualThreatId.IsManual(threat.InteractionKey);
                output.Append("### ").Append(Text(First(threat.Title, threat.TypeId, "Threat"))).Append("\n\n");
                Field(output, "ID", entry.Key);
                Field(output, "Status", State(threat.State));
                Field(output, "Priority", First(threat.Priority, "Unprioritized"));
                Field(output, "Category", First(threat.UserThreatCategory, "Uncategorized"));
                Field(output, "Origin", manual ? "Manual entry" : "Rule " + threat.TypeId);
                if (!manual && stale.Contains(entry.Key))
                {
                    Field(output, "Standing", "Stale: no longer reported by this rule set");
                }

                Field(output, "Diagram ID", threat.DrawingSurfaceGuid == Guid.Empty ? null : threat.DrawingSurfaceGuid.ToString("D"));
                string scope = string.Join(", ", new[] { threat.SourceGuid, threat.TargetGuid, threat.FlowGuid }
                    .Where(id => id != Guid.Empty).Distinct().Select(id => Resolve(id, names)));
                Field(output, "Scope", First(threat.InteractionString, scope, "Model-wide"));
                Field(output, "Description", First(threat.UserThreatDescription, threat.UserThreatShortDescription));
                Field(output, "Suggested mitigation", First(Property(threat, "Mitigation"), "Not documented."));
                Field(output, "References", First(Property(threat, "References"), "None"));
                Field(output, "Decision note", threat.StateInformation);
                output.Append('\n');
            }

            output.Append("\nGenerated by Threat Model Forge.\n");
            return output.ToString();
        }

        private static void Field(StringBuilder output, string label, string? value)
        {
            if (!string.IsNullOrWhiteSpace(value))
            {
                output.Append("- **").Append(label).Append(":** ").Append(Text(value)).Append('\n');
            }
        }

        private static string Text(string? value)
        {
            StringBuilder output = new StringBuilder();
            foreach (char character in (value ?? string.Empty).Replace("\r\n", "\n").Replace('\r', '\n'))
            {
                if (character == '\n')
                {
                    output.Append("<br />");
                }
                else if ("&<>\"'\\`*_{}[]()#+!|~:@".IndexOf(character) >= 0)
                {
                    output.Append("&#").Append(((int)character).ToString(CultureInfo.InvariantCulture)).Append(';');
                }
                else
                {
                    output.Append(character);
                }
            }

            return output.ToString();
        }

        private static string Name(Entity entity) => First(
            entity.Properties.OfType<StringDisplayAttribute>()
                .Where(property => string.Equals(property.DisplayName, "Name", StringComparison.OrdinalIgnoreCase))
                .Select(property => property.Value as string).FirstOrDefault(value => !string.IsNullOrWhiteSpace(value)),
            entity.Properties.OfType<HeaderDisplayAttribute>().Select(property => property.DisplayName)
                .FirstOrDefault(value => !string.IsNullOrWhiteSpace(value)),
            entity.Guid.ToString("D"));

        private static string Resolve(Guid id, IReadOnlyDictionary<Guid, string> names) =>
            names.TryGetValue(id, out string? name) ? name + " (" + id.ToString("D") + ")" : id.ToString("D");

        private static string Property(Threat threat, string name)
        {
            if (threat.Properties != null && threat.Properties.TryGetValue(name, out string? value) && !string.IsNullOrWhiteSpace(value))
            {
                return value!;
            }

            return threat.Properties?.FirstOrDefault(property =>
                string.Equals(property.Key, name, StringComparison.OrdinalIgnoreCase) && !string.IsNullOrWhiteSpace(property.Value)).Value ?? string.Empty;
        }

        private static string First(params string?[] values) => values.FirstOrDefault(value => !string.IsNullOrWhiteSpace(value)) ?? string.Empty;

        private static string State(ThreatState state) => state switch
        {
            ThreatState.AutoGenerated => "Open",
            ThreatState.NeedsInvestigation => "Needs Investigation",
            ThreatState.Mitigated => "Mitigated",
            ThreatState.NotApplicable => "Accepted",
            _ => state.ToString(),
        };
    }
}
