namespace ThreatModelForge.Analysis
{
    using System;
    using System.Collections.ObjectModel;

    /// <summary>
    /// The portion of a <see cref="ModelReport"/> containing information about the run of one rule.
    /// </summary>
    public class RuleReport
    {
        /// <summary>
        /// Gets or sets the rule ID.
        /// </summary>
        public string? ID { get; set; }

        /// <summary>
        /// Gets or sets the name of the rule.
        /// </summary>
        /// <remarks>
        /// This is always the <see cref="System.Reflection.MemberInfo.Name"/> of the <see cref="Rule"/> w/o
        /// the namespace.
        /// </remarks>
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the full description of the rule.
        /// </summary>
        /// <remarks>
        /// This is human readable text that describes what the rule is evaluating and why.
        /// </remarks>
        public string? FullDescription { get; set; }

        /// <summary>
        /// Gets or sets the help text for the rule.
        /// </summary>
        /// <remarks>
        /// This is human readable documentation describing how a user can fix the problem
        /// flagged by the rule.
        /// </remarks>
        public string? HelpText { get; set; }

        /// <summary>
        /// Gets or sets the help URL for the rule.
        /// </summary>
        public Uri? HelpUri { get; set; }

        /// <summary>
        /// Gets or sets the analyzer id (DLL name w/o extension).
        /// </summary>
        public string? AnalyzerId { get; set; }

        /// <summary>
        /// Gets or sets the severity of the rule.
        /// </summary>
        public MessageSeverity Severity { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the rule is disabled or not.
        /// </summary>
        public bool Disabled { get; set; }

        /// <summary>
        /// Gets the messages generated by the rule during this run.
        /// </summary>
        public Collection<RuleReportMessage> Messages { get; } = new Collection<RuleReportMessage>();

        /// <summary>
        /// Gets the messages that were suppressed for this rule during this run.
        /// </summary>
        public Collection<RuleReportMessage> SuppressedMessages { get; } = new Collection<RuleReportMessage>();

        /// <summary>
        /// Creates an empty report from the rule.
        /// </summary>
        /// <param name="rule">The source rule.</param>
        /// <returns>A new instance of the <see cref="RuleReport"/> class.</returns>
        public static RuleReport FromRule(Rule rule)
        {
            if (rule == null)
            {
                throw new ArgumentNullException(nameof(rule));
            }

            return new RuleReport
            {
                ID = rule.ID,
                Name = rule.GetType().Name,
                AnalyzerId = rule.GetType().Assembly.FullName,
                Severity = rule.Severity,
                Disabled = rule.Disabled,
                FullDescription = rule.FullDescription ?? string.Empty,
                HelpText = rule.HelpText ?? string.Empty,
                HelpUri = rule.HelpUri,
            };
        }
    }
}
