namespace ThreatModelForge.Analysis
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using ThreatModelForge.KnowledgeBase;
    using ThreatModelForge.Model;
    using ThreatModelForge.Model.Abstracts;

    /// <summary>
    /// Projects the validation findings of a model into its persistent threat register. Detection is
    /// <em>entirely</em> the rule set's job — this class does not re-implement any condition. It runs
    /// the same rules that <c>analyze</c> runs, keeps only the findings from threat-bearing rules (those
    /// whose rule declares a threat category), frames each as a threat against its element or
    /// flow, and upserts it into the model with an idempotent, triage-preserving write. The difference
    /// between a finding and a threat is lifecycle: a finding is transient and gated; a threat is
    /// persisted and triaged (open -> mitigated -> accepted).
    /// </summary>
    public static class ThreatGenerator
    {
        /// <summary>Generates threats by running the default rule set over the model.</summary>
        /// <param name="model">The model to analyze.</param>
        /// <returns>The generated threats.</returns>
        public static GenerationResult Generate(ThreatModel model)
        {
            using (RuleSet ruleSet = LoadDefaultRuleSet())
            {
                return Generate(model, ruleSet);
            }
        }

        /// <summary>Generates threats by projecting the given rule set's findings over the model.</summary>
        /// <param name="model">The model to analyze.</param>
        /// <param name="ruleSet">The rule set whose findings are projected (the detection source).</param>
        /// <returns>The generated threats.</returns>
        public static GenerationResult Generate(ThreatModel model, RuleSet ruleSet)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (ruleSet == null)
            {
                throw new ArgumentNullException(nameof(ruleSet));
            }

            FindingCollector collector = new FindingCollector();
            RuleEvaluationContext context = new RuleEvaluationContext(model, collector);
            ruleSet.Evaluate(context);

            return Project(collector.Messages);
        }

        /// <summary>
        /// Projects threats from messages a rule set has already produced. This is the projection half
        /// of <see cref="Generate(ThreatModel, RuleSet)"/>, split out so a caller that needs both the
        /// findings and the threats of one analysis evaluates the rules once and derives both from the
        /// same messages, instead of running the same detection twice.
        /// </summary>
        /// <param name="messages">The messages collected from one rule-set evaluation.</param>
        /// <returns>The generated threats, in stable order.</returns>
        public static GenerationResult Project(IEnumerable<Message> messages)
        {
            if (messages == null)
            {
                throw new ArgumentNullException(nameof(messages));
            }

            List<GeneratedThreat> threats = new List<GeneratedThreat>();
            HashSet<string> seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (Message message in messages)
            {
                Rule? rule = message.Source;
                Entity? target = message.Target;
                if (rule == null || target == null)
                {
                    continue;
                }

                if (rule.ThreatCategory is not RuleThreatCategory category)
                {
                    continue;
                }

                GeneratedThreat threat = ToThreat(message, rule, target, category);
                if (seen.Add(threat.Id))
                {
                    threats.Add(threat);
                }
            }

            threats.Sort(CompareThreats);
            return new GenerationResult(threats);
        }

        /// <summary>
        /// Idempotently writes the generated threats into the model's register. Threats are keyed by
        /// <c>{targetGuid:N}:{ruleId}</c>, so re-running updates in place: a human-triaged threat (any
        /// state other than <see cref="ThreatState.AutoGenerated"/>, including an accepted risk) is
        /// preserved while any missing rule-owned metadata is hydrated, an existing auto-generated
        /// threat is refreshed, and a newly-detected threat is added. Nothing is deleted, so no triage
        /// or author-supplied value is ever lost.
        /// </summary>
        /// <param name="model">The model whose register is updated.</param>
        /// <param name="result">The generation result to apply.</param>
        /// <returns>A summary of the changes made.</returns>
        public static ApplyResult Apply(ThreatModel model, GenerationResult result)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (result == null)
            {
                throw new ArgumentNullException(nameof(result));
            }

            int added = 0;
            int updated = 0;
            int preserved = 0;
            int nextId = NextThreatId(model);
            foreach (GeneratedThreat threat in result.Threats)
            {
                if (model.AllThreatsDictionary.TryGetValue(threat.Id, out Threat? existing))
                {
                    if (existing.State != ThreatState.AutoGenerated)
                    {
                        HydrateThreat(existing, threat);
                        preserved++;
                        continue;
                    }

                    UpdateThreat(existing, threat);
                    updated++;
                }
                else
                {
                    model.AllThreatsDictionary[threat.Id] = CreateThreat(threat, nextId);
                    nextId++;
                    added++;
                }
            }

            model.ThreatGenerationEnabled = true;
            return new ApplyResult { Added = added, Updated = updated, Preserved = preserved };
        }

        /// <summary>
        /// Records risk acceptance for a threat: moves it to <see cref="ThreatState.NotApplicable"/>
        /// and stores the justification. The threat stays visible in the register and report but is no
        /// longer treated as open. Because acceptance is per-threat (one rule finding on one element or
        /// flow), it can never silently swallow an unrelated finding.
        /// </summary>
        /// <param name="model">The model containing the threat.</param>
        /// <param name="threatId">The threat identifier (its register key, interaction key, or numeric id).</param>
        /// <param name="reason">The justification for accepting the risk.</param>
        /// <returns><see langword="true"/> if a matching threat was found and accepted; otherwise <see langword="false"/>.</returns>
        public static bool Accept(ThreatModel model, string threatId, string reason)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(threatId))
            {
                throw new ArgumentException("Value cannot be null or empty.", nameof(threatId));
            }

            Threat? threat = FindThreat(model, threatId);
            if (threat == null)
            {
                return false;
            }

            threat.State = ThreatState.NotApplicable;
            threat.StateInformation = reason ?? string.Empty;
            threat.ModifiedAt = DateTime.UtcNow;
            return true;
        }

        /// <summary>
        /// Adds a manually-authored threat to the model's register — a threat the rules do not detect.
        /// It is keyed in the reserved <c>manual:</c> namespace (so rule generation never collides with
        /// or overwrites it), scoped to the given element/flow ids, and carries the author's category,
        /// title, state, priority, description, and mitigation.
        /// </summary>
        /// <param name="model">The model to add the threat to.</param>
        /// <param name="category">The STRIDE category.</param>
        /// <param name="title">The threat statement.</param>
        /// <param name="elementIds">The element/flow ids the threat is scoped to (source, then optional target and flow); empty for a model-wide threat.</param>
        /// <param name="state">The initial lifecycle state.</param>
        /// <param name="priority">The priority, or <see langword="null"/> for the default.</param>
        /// <param name="description">The description, or <see langword="null"/>.</param>
        /// <param name="mitigation">The mitigation, or <see langword="null"/>.</param>
        /// <param name="id">
        /// The author's id for this threat, with or without the <c>manual:</c> prefix, or
        /// <see langword="null"/> to mint one. A supplied id that is already in the register is
        /// refused rather than overwriting the existing entry.
        /// </param>
        /// <returns>The created threat.</returns>
        public static Threat AddManual(
            ThreatModel model,
            string category,
            string title,
            IReadOnlyList<string>? elementIds,
            ThreatState state,
            string? priority,
            string? description,
            string? mitigation,
            string? id = null)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(title))
            {
                throw new ArgumentException("A threat title is required.", nameof(title));
            }

            string key = ResolveManualKey(model, id);
            (Guid source, Guid target, Guid flow) = ResolveScope(elementIds);
            Threat threat = new Threat
            {
                Id = NextThreatId(model),
                TypeId = null,
                SourceGuid = source,
                TargetGuid = target,
                FlowGuid = flow,
                DrawingSurfaceGuid = FirstSurfaceGuid(model),
                State = state,
                InteractionKey = key,
                Title = title,
                Priority = string.IsNullOrWhiteSpace(priority) ? "Medium" : priority,
                UserThreatCategory = string.IsNullOrWhiteSpace(category) ? null : category,
                UserThreatDescription = string.IsNullOrWhiteSpace(description) ? null : description,
                Wide = source == Guid.Empty && target == Guid.Empty && flow == Guid.Empty,
                ModifiedAt = DateTime.UtcNow,
            };
            if (!string.IsNullOrWhiteSpace(mitigation))
            {
                threat.Properties = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    ["Mitigation"] = mitigation!,
                };
            }

            model.AllThreatsDictionary[key] = threat;
            model.ThreatGenerationEnabled = true;
            return threat;
        }

        /// <summary>
        /// Edits a threat's author-owned fields in place: its lifecycle state, priority, title,
        /// description, mitigation, category, and state note. Only the non-null arguments are applied.
        /// Works on both rule-derived and manually-authored threats found in the register.
        /// </summary>
        /// <param name="model">The model containing the threat.</param>
        /// <param name="threatId">The threat's register key, interaction key, or numeric id.</param>
        /// <param name="state">The new lifecycle state, or <see langword="null"/> to leave it unchanged.</param>
        /// <param name="priority">The new priority, or <see langword="null"/> to leave it unchanged.</param>
        /// <param name="description">The new description, or <see langword="null"/> to leave it unchanged (empty clears it).</param>
        /// <param name="mitigation">The new mitigation, or <see langword="null"/> to leave it unchanged (empty clears it).</param>
        /// <param name="note">The new state note / justification, or <see langword="null"/> to leave it unchanged.</param>
        /// <param name="title">
        /// The new title, or <see langword="null"/> to leave it unchanged. Empty clears an override on a
        /// generated threat, restoring the title its rule produces.
        /// </param>
        /// <param name="category">
        /// The new category for a manually authored threat, or <see langword="null"/> to leave it
        /// unchanged.
        /// </param>
        /// <returns><see langword="true"/> if a matching threat was found and edited; otherwise <see langword="false"/>.</returns>
        /// <exception cref="ArgumentException">
        /// <paramref name="category"/> was supplied for a rule-derived threat, whose category belongs to
        /// the rule that detected it. Callers that surface errors to a person should check first rather
        /// than rely on the exception text.
        /// </exception>
        public static bool Edit(
            ThreatModel model,
            string threatId,
            ThreatState? state,
            string? priority,
            string? description,
            string? mitigation,
            string? note,
            string? title = null,
            string? category = null)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(threatId))
            {
                throw new ArgumentException("Value cannot be null or empty.", nameof(threatId));
            }

            Threat? threat = FindThreat(model, threatId);
            if (threat == null)
            {
                return false;
            }

            bool manual = ManualThreatId.IsManual(threat.InteractionKey);
            if (category != null && !manual)
            {
                throw new ArgumentException(
                    "The category of a generated threat belongs to the rule that detected it.",
                    nameof(category));
            }

            if (state.HasValue)
            {
                threat.State = state.Value;
            }

            if (title != null)
            {
                ApplyTitle(threat, title, manual);
            }

            if (category != null)
            {
                threat.UserThreatCategory = category;
            }

            if (!string.IsNullOrWhiteSpace(priority))
            {
                threat.Priority = priority;
                threat.Properties ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                threat.Properties["PriorityOverride"] = "true";
            }

            if (description != null)
            {
                threat.UserThreatDescription = description.Length == 0 ? null : description;
            }

            if (mitigation != null)
            {
                threat.Properties ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                if (mitigation.Length == 0)
                {
                    threat.Properties.Remove("Mitigation");
                }
                else
                {
                    threat.Properties["Mitigation"] = mitigation;
                }
            }

            if (note != null)
            {
                threat.StateInformation = note;
            }

            threat.ModifiedAt = DateTime.UtcNow;
            return true;
        }

        /// <summary>
        /// Removes a manually-authored threat from the register. Rule-derived threats regenerate from
        /// the rules and cannot be removed (accept or edit them instead).
        /// </summary>
        /// <param name="model">The model containing the threat.</param>
        /// <param name="threatId">The threat's register key, interaction key, or numeric id.</param>
        /// <returns><see langword="true"/> if a manual threat was found and removed; otherwise <see langword="false"/>.</returns>
        public static bool Remove(ThreatModel model, string threatId) => Remove(model, threatId, null);

        /// <summary>
        /// Removes a manually-authored threat, or a rule-derived threat the supplied register summary
        /// classifies as stale.
        /// </summary>
        /// <remarks>
        /// A rule-derived threat that the rules still produce cannot be removed: it would reappear on
        /// the next run, so refusing is more honest than pretending. A <em>stale</em> one will not
        /// reappear, which is exactly why it needs an explicit way out. Removal is never automatic —
        /// the caller must have classified the register and asked for this entry by name.
        /// </remarks>
        /// <param name="model">The model containing the threat.</param>
        /// <param name="threatId">The threat's register key, interaction key, or numeric id.</param>
        /// <param name="register">
        /// The classified register, or <see langword="null"/> to allow manual threats only.
        /// </param>
        /// <returns><see langword="true"/> if a threat was found and removed; otherwise <see langword="false"/>.</returns>
        public static bool Remove(ThreatModel model, string threatId, ThreatRegisterSummary? register)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(threatId))
            {
                throw new ArgumentException("Value cannot be null or empty.", nameof(threatId));
            }

            foreach (KeyValuePair<string, Threat> pair in model.AllThreatsDictionary)
            {
                string interaction = string.IsNullOrEmpty(pair.Value.InteractionKey) ? pair.Key : pair.Value.InteractionKey!;
                bool manual = interaction.StartsWith(ManualThreatId.Prefix, StringComparison.OrdinalIgnoreCase);
                bool matches =
                    string.Equals(pair.Key, threatId, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(interaction, threatId, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(pair.Value.Id.ToString(CultureInfo.InvariantCulture), threatId, StringComparison.Ordinal);
                if (matches)
                {
                    if (!manual && !IsStale(register, interaction))
                    {
                        return false;
                    }

                    model.AllThreatsDictionary.Remove(pair.Key);
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Removes every stale entry from the register.
        /// </summary>
        /// <remarks>
        /// Entries carrying triage are kept unless <paramref name="discardTriage"/> is set, and are
        /// reported back either way. Losing a rule is not a reason to lose the decision someone
        /// recorded against it, so discarding that has to be asked for.
        /// </remarks>
        /// <param name="model">The model whose register is pruned.</param>
        /// <param name="register">The classified register identifying the stale entries.</param>
        /// <param name="discardTriage">Whether to also remove stale entries that carry triage.</param>
        /// <returns>What was removed and what was kept.</returns>
        public static StaleRemovalResult RemoveStale(
            ThreatModel model,
            ThreatRegisterSummary register,
            bool discardTriage)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (register == null)
            {
                throw new ArgumentNullException(nameof(register));
            }

            List<string> removed = new List<string>();
            List<string> retained = new List<string>();
            foreach (ThreatRegisterEntry entry in register.Entries)
            {
                if (entry.State != ThreatRegisterStates.StaleGenerated)
                {
                    continue;
                }

                if (entry.HasTriage && !discardTriage)
                {
                    retained.Add(entry.Id);
                    continue;
                }

                if (RemoveByKey(model, entry.Id))
                {
                    removed.Add(entry.Id);
                }
            }

            return new StaleRemovalResult { Removed = removed, RetainedWithTriage = retained };
        }

        private static bool IsStale(ThreatRegisterSummary? register, string interaction)
        {
            if (register == null)
            {
                return false;
            }

            foreach (ThreatRegisterEntry entry in register.Entries)
            {
                if (string.Equals(entry.Id, interaction, StringComparison.OrdinalIgnoreCase))
                {
                    return entry.State == ThreatRegisterStates.StaleGenerated;
                }
            }

            return false;
        }

        private static bool RemoveByKey(ThreatModel model, string key)
        {
            foreach (KeyValuePair<string, Threat> pair in model.AllThreatsDictionary)
            {
                string interaction = string.IsNullOrEmpty(pair.Value.InteractionKey) ? pair.Key : pair.Value.InteractionKey!;
                if (string.Equals(interaction, key, StringComparison.OrdinalIgnoreCase))
                {
                    model.AllThreatsDictionary.Remove(pair.Key);
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Resolves the register key for a new manual threat: the author's id when they supplied one,
        /// otherwise a fresh one.
        /// </summary>
        /// <remarks>
        /// A supplied id that is already taken is refused rather than overwriting what is there. The
        /// author is asserting an identity, and silently replacing an existing threat — losing its
        /// triage, its justification, and its history — is the opposite of what they asked for.
        /// </remarks>
        /// <param name="model">The model whose register the threat joins.</param>
        /// <param name="supplied">The author's id, or <see langword="null"/> to mint one.</param>
        /// <returns>The register key to use.</returns>
        private static string ResolveManualKey(ThreatModel model, string? supplied)
        {
            if (supplied == null)
            {
                return ManualThreatId.Create();
            }

            if (!ManualThreatId.TryCanonicalize(supplied, out string key, out string? error))
            {
                throw new ArgumentException(error, nameof(supplied));
            }

            if (model.AllThreatsDictionary.ContainsKey(key))
            {
                throw new ArgumentException(
                    $"The threat id '{key}' is already in this model's register.",
                    nameof(supplied));
            }

            return key;
        }

        private static (Guid Source, Guid Target, Guid Flow) ResolveScope(IReadOnlyList<string>? elementIds)
        {
            Guid source = Guid.Empty;
            Guid target = Guid.Empty;
            Guid flow = Guid.Empty;
            if (elementIds != null)
            {
                if (elementIds.Count > 0)
                {
                    Guid.TryParse(elementIds[0], out source);
                }

                if (elementIds.Count > 1)
                {
                    Guid.TryParse(elementIds[1], out target);
                }

                if (elementIds.Count > 2)
                {
                    Guid.TryParse(elementIds[2], out flow);
                }
            }

            return (source, target, flow);
        }

        private static Guid FirstSurfaceGuid(ThreatModel model)
        {
            foreach (DrawingSurfaceModel surface in model.DrawingSurfaceList)
            {
                return surface.Guid;
            }

            return Guid.Empty;
        }

        private static RuleSet LoadDefaultRuleSet()
        {
            return AnalysisRuleSources.Create();
        }

        private static GeneratedThreat ToThreat(Message message, Rule rule, Entity target, RuleThreatCategory category)
        {
            bool isFlow = target is Connector;
            Guid sourceGuid = target.Guid;
            Guid targetGuid = Guid.Empty;
            Guid flowGuid = Guid.Empty;
            string? sourceName = NameOf(target);
            string? targetName = null;
            string? flowName = null;
            string interactionString = sourceName ?? target.Guid.ToString();

            if (target is Connector connector)
            {
                sourceGuid = connector.SourceGuid;
                targetGuid = connector.TargetGuid;
                flowGuid = connector.Guid;
                flowName = NameOf(connector);
                sourceName = NameInDiagram(message.Model, connector.SourceGuid);
                targetName = NameInDiagram(message.Model, connector.TargetGuid);
                interactionString = (sourceName ?? "?") + " -> " + (targetName ?? "?");
            }

            return new GeneratedThreat
            {
                Id = string.Format(CultureInfo.InvariantCulture, "{0:N}:{1}", target.Guid, rule.ID),
                RuleId = rule.ID,
                Category = rule.Stride ?? StrideCategory.Unknown,
                ThreatCategory = category,
                Title = message.Text ?? rule.FullDescription,
                Mitigation = string.IsNullOrWhiteSpace(rule.HelpText) ? null : rule.HelpText,
                Severity = rule.Severity.ToString().ToLowerInvariant(),
                Priority = rule.DefaultThreatPriority?.ToString() ?? PriorityFor(rule.Severity),
                References = rule.ThreatReferences,
                SourceGuid = sourceGuid,
                TargetGuid = targetGuid,
                FlowGuid = flowGuid,
                DiagramGuid = message.Model?.Guid ?? Guid.Empty,
                SourceName = sourceName,
                TargetName = targetName,
                FlowName = flowName,
                IsFlowScoped = isFlow,
                InteractionString = interactionString,
            };
        }

        private static Threat CreateThreat(GeneratedThreat threat, int id)
        {
            return new Threat
            {
                Id = id,
                TypeId = threat.RuleId,
                SourceGuid = threat.SourceGuid,
                TargetGuid = threat.TargetGuid,
                FlowGuid = threat.FlowGuid,
                DrawingSurfaceGuid = threat.DiagramGuid,
                State = ThreatState.AutoGenerated,
                InteractionKey = threat.Id,
                InteractionString = threat.InteractionString,
                Title = threat.Title,
                Priority = threat.Priority,
                UserThreatCategory = threat.ThreatCategory.Name,
                StateInformation = string.Empty,
                ModifiedAt = DateTime.UtcNow,
                Properties = BuildProperties(threat),
            };
        }

        private static void UpdateThreat(Threat existing, GeneratedThreat threat)
        {
            bool priorityOverridden = HasPriorityOverride(existing, threat);
            string? overriddenPriority = priorityOverridden ? existing.Priority : null;
            bool titleOverridden = HasTitleOverride(existing);
            string? overriddenTitle = titleOverridden ? existing.Title : null;
            existing.TypeId = threat.RuleId;
            existing.SourceGuid = threat.SourceGuid;
            existing.TargetGuid = threat.TargetGuid;
            existing.FlowGuid = threat.FlowGuid;
            existing.DrawingSurfaceGuid = threat.DiagramGuid;
            existing.InteractionKey = threat.Id;
            existing.InteractionString = threat.InteractionString;
            existing.Title = overriddenTitle ?? threat.Title;
            existing.Priority = overriddenPriority ?? threat.Priority;
            existing.UserThreatCategory = threat.ThreatCategory.Name;
            existing.Properties = BuildProperties(threat);
            if (priorityOverridden)
            {
                existing.Properties["PriorityOverride"] = "true";
            }

            if (titleOverridden)
            {
                existing.Properties["TitleOverride"] = "true";
            }

            existing.ModifiedAt = DateTime.UtcNow;
        }

        private static void HydrateThreat(Threat existing, GeneratedThreat threat)
        {
            bool priorityOverridden = HasPriorityOverride(existing, threat);
            bool titleOverridden = HasTitleOverride(existing);
            existing.TypeId = threat.RuleId;
            existing.SourceGuid = threat.SourceGuid;
            existing.TargetGuid = threat.TargetGuid;
            existing.FlowGuid = threat.FlowGuid;
            existing.DrawingSurfaceGuid = threat.DiagramGuid;
            existing.InteractionKey = threat.Id;
            existing.InteractionString = threat.InteractionString;
            existing.Title = titleOverridden ? existing.Title : FirstNonEmpty(existing.Title, threat.Title);
            existing.Priority = priorityOverridden ? existing.Priority : threat.Priority;
            existing.UserThreatCategory = threat.ThreatCategory.Name;

            Dictionary<string, string> generatedProperties = BuildProperties(threat);
            foreach (KeyValuePair<string, string> property in existing.Properties ?? new Dictionary<string, string>())
            {
                if (!IsRuleOwnedProperty(property.Key))
                {
                    generatedProperties[property.Key] = property.Value;
                }
            }

            if (priorityOverridden)
            {
                generatedProperties["PriorityOverride"] = "true";
            }

            if (titleOverridden)
            {
                generatedProperties["TitleOverride"] = "true";
            }

            existing.Properties = generatedProperties;
        }

        private static string FirstNonEmpty(string? current, string generated)
            => string.IsNullOrWhiteSpace(current) ? generated : current!;

        private static Dictionary<string, string> BuildProperties(GeneratedThreat threat)
        {
            Dictionary<string, string> props = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Rule"] = threat.RuleId,
                ["CategoryId"] = threat.ThreatCategory.Id,
                ["GeneratedDefaultPriority"] = threat.Priority,

                // Stashed for the same reason as the default priority: it is the only way to tell an
                // author's title from the rule's on a later run, including one where the title was
                // changed in another tool that cannot write tmforge's override marker.
                ["GeneratedDefaultTitle"] = threat.Title,
            };
            if (threat.Stride.HasValue)
            {
                props["STRIDE"] = threat.Stride.Value.ToString();
            }

            if (!string.IsNullOrWhiteSpace(threat.Mitigation))
            {
                props["Mitigation"] = threat.Mitigation!;
            }

            if (threat.References.Count > 0)
            {
                props["References"] = string.Join(", ", threat.References.Select(r => r.Id));
            }

            return props;
        }

        private static bool HasPriorityOverride(Threat existing, GeneratedThreat generated)
        {
            if (existing.Properties?.TryGetValue("PriorityOverride", out string? marker) == true &&
                string.Equals(marker, "true", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (string.IsNullOrWhiteSpace(existing.Priority))
            {
                return false;
            }

            if (existing.Properties?.TryGetValue("GeneratedDefaultPriority", out string? previousDefault) == true)
            {
                return !string.Equals(existing.Priority, previousDefault, StringComparison.OrdinalIgnoreCase);
            }

            if (existing.State == ThreatState.AutoGenerated)
            {
                return false;
            }

            return !string.Equals(
                existing.Priority,
                LegacyPriorityFor(generated.Severity),
                StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Applies a title edit, recording that the title is now the author's.
        /// </summary>
        /// <remarks>
        /// Clearing a generated threat's title restores the rule's own wording from the stashed
        /// default, which is what makes the edit reversible: an author who changes their mind gets the
        /// rule's title back rather than an empty one. A manual threat has no rule to fall back to, so
        /// its caller refuses a blank title before reaching here.
        /// </remarks>
        /// <param name="threat">The threat being edited.</param>
        /// <param name="title">The requested title; empty clears an override.</param>
        /// <param name="manual">Whether the threat is manually authored.</param>
        private static void ApplyTitle(Threat threat, string title, bool manual)
        {
            if (title.Trim().Length > 0)
            {
                threat.Title = title;
                if (!manual)
                {
                    threat.Properties ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                    threat.Properties["TitleOverride"] = "true";
                }

                return;
            }

            if (manual)
            {
                return;
            }

            threat.Properties?.Remove("TitleOverride");
            if (threat.Properties?.TryGetValue("GeneratedDefaultTitle", out string? generated) == true &&
                !string.IsNullOrEmpty(generated))
            {
                threat.Title = generated;
            }
        }

        /// <summary>
        /// Reports whether an existing threat's title is the author's rather than the rule's.
        /// </summary>
        /// <remarks>
        /// Mirrors <see cref="HasPriorityOverride"/>. The marker is the fast path for a title tmforge
        /// applied itself; comparing against the stashed generated default is what catches a title
        /// changed in another tool, which cannot write the marker. Without this, regeneration would
        /// quietly restore the rule's wording over the author's.
        /// </remarks>
        /// <param name="existing">The threat already in the register.</param>
        /// <returns><see langword="true"/> when the title is author-owned.</returns>
        private static bool HasTitleOverride(Threat existing)
        {
            if (existing.Properties?.TryGetValue("TitleOverride", out string? marker) == true &&
                string.Equals(marker, "true", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (string.IsNullOrWhiteSpace(existing.Title))
            {
                return false;
            }

            if (existing.Properties?.TryGetValue("GeneratedDefaultTitle", out string? previousDefault) == true)
            {
                return !string.Equals(existing.Title, previousDefault, StringComparison.Ordinal);
            }

            // No stashed default means this entry predates the override contract. Claiming an override
            // would freeze the rule's own wording as though an author had chosen it.
            return false;
        }

        private static bool IsRuleOwnedProperty(string name)
        {
            return string.Equals(name, "Rule", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(name, "CategoryId", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(name, "GeneratedDefaultPriority", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(name, "GeneratedDefaultTitle", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(name, "STRIDE", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(name, "References", StringComparison.OrdinalIgnoreCase);
        }

        private static string LegacyPriorityFor(string severity)
        {
            if (string.Equals(severity, "error", StringComparison.OrdinalIgnoreCase))
            {
                return "High";
            }

            return string.Equals(severity, "info", StringComparison.OrdinalIgnoreCase) ? "Low" : "Medium";
        }

        private static string PriorityFor(MessageSeverity severity)
        {
            switch (severity)
            {
                case MessageSeverity.Error:
                    return "High";
                case MessageSeverity.Info:
                    return "Low";
                default:
                    return "Medium";
            }
        }

        private static int NextThreatId(ThreatModel model)
        {
            int max = 0;
            foreach (Threat threat in model.AllThreatsDictionary.Values.Where(threat => threat.Id > max))
            {
                max = threat.Id;
            }

            return max + 1;
        }

        private static Threat? FindThreat(ThreatModel model, string threatId)
        {
            if (model.AllThreatsDictionary.TryGetValue(threatId, out Threat? byKey))
            {
                return byKey;
            }

            foreach (KeyValuePair<string, Threat> pair in model.AllThreatsDictionary)
            {
                if (string.Equals(pair.Value.InteractionKey, threatId, StringComparison.OrdinalIgnoreCase))
                {
                    return pair.Value;
                }

                if (string.Equals(pair.Value.Id.ToString(CultureInfo.InvariantCulture), threatId, StringComparison.Ordinal))
                {
                    return pair.Value;
                }
            }

            return null;
        }

        private static string? NameInDiagram(DrawingSurfaceModel? diagram, Guid id)
        {
            if (diagram != null && diagram.Borders.TryGetValue(id, out object? value) && value is Entity entity)
            {
                return NameOf(entity);
            }

            return null;
        }

        private static string? NameOf(Entity entity)
        {
            return entity.Name() ?? entity.HeaderName();
        }

        private static int CompareThreats(GeneratedThreat left, GeneratedThreat right)
        {
            if (left.Category == StrideCategory.Unknown && right.Category != StrideCategory.Unknown)
            {
                return 1;
            }

            if (left.Category != StrideCategory.Unknown && right.Category == StrideCategory.Unknown)
            {
                return -1;
            }

            int byCategory = left.Category.CompareTo(right.Category);
            if (left.Category == StrideCategory.Unknown && right.Category == StrideCategory.Unknown)
            {
                byCategory = string.Compare(left.ThreatCategory.Id, right.ThreatCategory.Id, StringComparison.Ordinal);
            }

            if (byCategory != 0)
            {
                return byCategory;
            }

            int byRule = string.CompareOrdinal(left.RuleId, right.RuleId);
            if (byRule != 0)
            {
                return byRule;
            }

            return string.CompareOrdinal(left.Id, right.Id);
        }
    }
}
