namespace ThreatModelForge.Analysis
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ThreatModelForge.KnowledgeBase;
    using ThreatModelForge.Model;

    /// <summary>
    /// Splits a model's threat register by origin and by standing against the current analysis.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="ThreatGenerator.Apply"/> never deletes, so a rule that stops firing leaves its entry
    /// in the register indefinitely. That is the right trade — deleting would throw away triage — but
    /// it means the register alone cannot tell a live finding from a leftover. This classifier answers
    /// that by comparing the stored register against one generation run.
    /// </para>
    /// <para>
    /// Staleness is only ever claimed when the rule was actually given a chance to fire. If a rule is
    /// missing from the effective bundle or disabled for the run, its entries are reported as
    /// indeterminate and the rule is named, because a rule that never ran says nothing about the
    /// model. Treating those as stale would invite deleting real findings after a mistyped
    /// <c>--rules</c> path or a disabled pack.
    /// </para>
    /// </remarks>
    public static class ThreatRegisterClassifier
    {
        /// <summary>
        /// Classifies the register against a generation result produced by the supplied rule set.
        /// </summary>
        /// <remarks>
        /// The caller passes the generation result and the rule set that produced it, so the counts are
        /// necessarily computed against one effective bundle rather than two independent runs.
        /// </remarks>
        /// <param name="model">The model whose register is classified.</param>
        /// <param name="generation">The current generation result from <paramref name="ruleSet"/>.</param>
        /// <param name="ruleSet">The effective rules that produced <paramref name="generation"/>.</param>
        /// <returns>The split summary.</returns>
        public static ThreatRegisterSummary Classify(
            ThreatModel model,
            GenerationResult generation,
            RuleSet ruleSet)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (generation == null)
            {
                throw new ArgumentNullException(nameof(generation));
            }

            if (ruleSet == null)
            {
                throw new ArgumentNullException(nameof(ruleSet));
            }

            HashSet<string> produced = new HashSet<string>(
                generation.Threats.Select(threat => threat.Id),
                StringComparer.OrdinalIgnoreCase);
            HashSet<string> evaluated = new HashSet<string>(
                ruleSet.Rules.Where(rule => !rule.Disabled).Select(rule => rule.ID),
                StringComparer.OrdinalIgnoreCase);

            List<ThreatRegisterEntry> entries = new List<ThreatRegisterEntry>();
            SortedSet<string> unavailable = new SortedSet<string>(StringComparer.Ordinal);
            int manual = 0;
            int persisted = 0;
            int stale = 0;
            int indeterminate = 0;

            foreach (KeyValuePair<string, Threat> pair in model.AllThreatsDictionary)
            {
                Threat threat = pair.Value;
                string key = string.IsNullOrEmpty(threat.InteractionKey) ? pair.Key : threat.InteractionKey!;
                bool hasTriage = threat.State != ThreatState.AutoGenerated;

                if (ManualThreatId.IsManual(key) || string.IsNullOrWhiteSpace(threat.TypeId))
                {
                    manual++;
                    entries.Add(new ThreatRegisterEntry
                    {
                        Id = key,
                        State = ThreatRegisterStates.Manual,
                        RuleId = null,
                        Title = threat.Title ?? string.Empty,
                        Triage = threat.State,
                        HasTriage = hasTriage,
                    });
                    continue;
                }

                persisted++;
                string ruleId = threat.TypeId!;
                string state;
                if (produced.Contains(key))
                {
                    state = ThreatRegisterStates.CurrentGenerated;
                }
                else if (evaluated.Contains(ruleId))
                {
                    state = ThreatRegisterStates.StaleGenerated;
                    stale++;
                }
                else
                {
                    state = ThreatRegisterStates.IndeterminateGenerated;
                    indeterminate++;
                    unavailable.Add(ruleId);
                }

                entries.Add(new ThreatRegisterEntry
                {
                    Id = key,
                    State = state,
                    RuleId = ruleId,
                    Title = threat.Title ?? string.Empty,
                    Triage = threat.State,
                    HasTriage = hasTriage,
                });
            }

            return new ThreatRegisterSummary
            {
                Manual = manual,
                PersistedGenerated = persisted,
                CurrentGenerated = generation.Threats.Count,
                StaleGenerated = stale,
                IndeterminateGenerated = indeterminate,
                UnavailableRuleIds = unavailable.ToList(),
                Entries = entries,
            };
        }
    }
}
