namespace ThreatModelForge.Analysis
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using ThreatModelForge.KnowledgeBase;
    using ThreatModelForge.Model;
    using ThreatModelForge.Model.Abstracts;

    /// <summary>
    /// Projects the validation findings of a model into its persistent threat register. Detection is
    /// <em>entirely</em> the rule set's job — this class does not re-implement any condition. It runs
    /// the same rules that <c>analyze</c> runs, keeps only the findings from threat-bearing rules (those
    /// whose rule declares a STRIDE category), frames each as a STRIDE threat against its element or
    /// flow, and upserts it into the model with an idempotent, triage-preserving write. The difference
    /// between a finding and a threat is lifecycle: a finding is transient and gated; a threat is
    /// persisted and triaged (open -> mitigated -> accepted).
    /// </summary>
    public static class ThreatGenerator
    {
        /// <summary>Generates threats by running the default rule set over the model.</summary>
        /// <param name="model">The model to analyze.</param>
        /// <returns>The generated threats.</returns>
        public static GenerationResult Generate(ThreatModel model)
        {
            using (RuleSet ruleSet = LoadDefaultRuleSet())
            {
                return Generate(model, ruleSet);
            }
        }

        /// <summary>Generates threats by projecting the given rule set's findings over the model.</summary>
        /// <param name="model">The model to analyze.</param>
        /// <param name="ruleSet">The rule set whose findings are projected (the detection source).</param>
        /// <returns>The generated threats.</returns>
        public static GenerationResult Generate(ThreatModel model, RuleSet ruleSet)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (ruleSet == null)
            {
                throw new ArgumentNullException(nameof(ruleSet));
            }

            FindingCollector collector = new FindingCollector();
            RuleEvaluationContext context = new RuleEvaluationContext(model, collector);
            ruleSet.Evaluate(context);

            List<GeneratedThreat> threats = new List<GeneratedThreat>();
            HashSet<string> seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (Message message in collector.Messages)
            {
                Rule? rule = message.Source;
                Entity? target = message.Target;
                if (rule == null || target == null)
                {
                    continue;
                }

                if (rule.Stride is not StrideCategory category)
                {
                    continue;
                }

                GeneratedThreat threat = ToThreat(message, rule, target, category);
                if (seen.Add(threat.Id))
                {
                    threats.Add(threat);
                }
            }

            threats.Sort(CompareThreats);
            return new GenerationResult(threats);
        }

        /// <summary>
        /// Idempotently writes the generated threats into the model's register. Threats are keyed by
        /// <c>{targetGuid:N}:{ruleId}</c>, so re-running updates in place: a human-triaged threat (any
        /// state other than <see cref="ThreatState.AutoGenerated"/>, including an accepted risk) is
        /// preserved untouched, an existing auto-generated threat is refreshed, and a newly-detected
        /// threat is added. Nothing is deleted, so no triage is ever lost.
        /// </summary>
        /// <param name="model">The model whose register is updated.</param>
        /// <param name="result">The generation result to apply.</param>
        /// <returns>A summary of the changes made.</returns>
        public static ApplyResult Apply(ThreatModel model, GenerationResult result)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (result == null)
            {
                throw new ArgumentNullException(nameof(result));
            }

            int added = 0;
            int updated = 0;
            int preserved = 0;
            int nextId = NextThreatId(model);
            foreach (GeneratedThreat threat in result.Threats)
            {
                if (model.AllThreatsDictionary.TryGetValue(threat.Id, out Threat? existing))
                {
                    if (existing.State != ThreatState.AutoGenerated)
                    {
                        preserved++;
                        continue;
                    }

                    UpdateThreat(existing, threat);
                    updated++;
                }
                else
                {
                    model.AllThreatsDictionary[threat.Id] = CreateThreat(threat, nextId);
                    nextId++;
                    added++;
                }
            }

            model.ThreatGenerationEnabled = true;
            return new ApplyResult { Added = added, Updated = updated, Preserved = preserved };
        }

        /// <summary>
        /// Records risk acceptance for a threat: moves it to <see cref="ThreatState.NotApplicable"/>
        /// and stores the justification. The threat stays visible in the register and report but is no
        /// longer treated as open. Because acceptance is per-threat (one rule finding on one element or
        /// flow), it can never silently swallow an unrelated finding.
        /// </summary>
        /// <param name="model">The model containing the threat.</param>
        /// <param name="threatId">The threat identifier (its register key, interaction key, or numeric id).</param>
        /// <param name="reason">The justification for accepting the risk.</param>
        /// <returns><see langword="true"/> if a matching threat was found and accepted; otherwise <see langword="false"/>.</returns>
        public static bool Accept(ThreatModel model, string threatId, string reason)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(threatId))
            {
                throw new ArgumentException("Value cannot be null or empty.", nameof(threatId));
            }

            Threat? threat = FindThreat(model, threatId);
            if (threat == null)
            {
                return false;
            }

            threat.State = ThreatState.NotApplicable;
            threat.StateInformation = reason ?? string.Empty;
            threat.ModifiedAt = DateTime.UtcNow;
            return true;
        }

        /// <summary>
        /// Adds a manually-authored threat to the model's register — a threat the rules do not detect.
        /// It is keyed with a stable <c>manual:{guid}</c> id (so rule generation never collides with or
        /// overwrites it), scoped to the given element/flow ids, and carries the author's category,
        /// title, state, priority, description, and mitigation.
        /// </summary>
        /// <param name="model">The model to add the threat to.</param>
        /// <param name="category">The STRIDE category.</param>
        /// <param name="title">The threat statement.</param>
        /// <param name="elementIds">The element/flow ids the threat is scoped to (source, then optional target and flow); empty for a model-wide threat.</param>
        /// <param name="state">The initial lifecycle state.</param>
        /// <param name="priority">The priority, or <see langword="null"/> for the default.</param>
        /// <param name="description">The description, or <see langword="null"/>.</param>
        /// <param name="mitigation">The mitigation, or <see langword="null"/>.</param>
        /// <returns>The created threat.</returns>
        public static Threat AddManual(
            ThreatModel model,
            string category,
            string title,
            IReadOnlyList<string>? elementIds,
            ThreatState state,
            string? priority,
            string? description,
            string? mitigation)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(title))
            {
                throw new ArgumentException("A threat title is required.", nameof(title));
            }

            (Guid source, Guid target, Guid flow) = ResolveScope(elementIds);
            string key = "manual:" + Guid.NewGuid().ToString("N");
            Threat threat = new Threat
            {
                Id = NextThreatId(model),
                TypeId = null,
                SourceGuid = source,
                TargetGuid = target,
                FlowGuid = flow,
                DrawingSurfaceGuid = FirstSurfaceGuid(model),
                State = state,
                InteractionKey = key,
                Title = title,
                Priority = string.IsNullOrWhiteSpace(priority) ? "Medium" : priority,
                UserThreatCategory = string.IsNullOrWhiteSpace(category) ? null : category,
                UserThreatDescription = string.IsNullOrWhiteSpace(description) ? null : description,
                Wide = source == Guid.Empty && target == Guid.Empty && flow == Guid.Empty,
                ModifiedAt = DateTime.UtcNow,
            };
            if (!string.IsNullOrWhiteSpace(mitigation))
            {
                threat.Properties = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    ["Mitigation"] = mitigation!,
                };
            }

            model.AllThreatsDictionary[key] = threat;
            model.ThreatGenerationEnabled = true;
            return threat;
        }

        /// <summary>
        /// Edits a threat's author-owned fields in place: its lifecycle state, priority, description,
        /// mitigation, and state note. Only the non-null arguments are applied. Works on both
        /// rule-derived and manually-authored threats found in the register.
        /// </summary>
        /// <param name="model">The model containing the threat.</param>
        /// <param name="threatId">The threat's register key, interaction key, or numeric id.</param>
        /// <param name="state">The new lifecycle state, or <see langword="null"/> to leave it unchanged.</param>
        /// <param name="priority">The new priority, or <see langword="null"/> to leave it unchanged.</param>
        /// <param name="description">The new description, or <see langword="null"/> to leave it unchanged (empty clears it).</param>
        /// <param name="mitigation">The new mitigation, or <see langword="null"/> to leave it unchanged (empty clears it).</param>
        /// <param name="note">The new state note / justification, or <see langword="null"/> to leave it unchanged.</param>
        /// <returns><see langword="true"/> if a matching threat was found and edited; otherwise <see langword="false"/>.</returns>
        public static bool Edit(
            ThreatModel model,
            string threatId,
            ThreatState? state,
            string? priority,
            string? description,
            string? mitigation,
            string? note)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(threatId))
            {
                throw new ArgumentException("Value cannot be null or empty.", nameof(threatId));
            }

            Threat? threat = FindThreat(model, threatId);
            if (threat == null)
            {
                return false;
            }

            if (state.HasValue)
            {
                threat.State = state.Value;
            }

            if (!string.IsNullOrWhiteSpace(priority))
            {
                threat.Priority = priority;
            }

            if (description != null)
            {
                threat.UserThreatDescription = description.Length == 0 ? null : description;
            }

            if (mitigation != null)
            {
                threat.Properties ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                if (mitigation.Length == 0)
                {
                    threat.Properties.Remove("Mitigation");
                }
                else
                {
                    threat.Properties["Mitigation"] = mitigation;
                }
            }

            if (note != null)
            {
                threat.StateInformation = note;
            }

            threat.ModifiedAt = DateTime.UtcNow;
            return true;
        }

        /// <summary>
        /// Removes a manually-authored threat from the register. Rule-derived threats regenerate from
        /// the rules and cannot be removed (accept or edit them instead).
        /// </summary>
        /// <param name="model">The model containing the threat.</param>
        /// <param name="threatId">The threat's register key, interaction key, or numeric id.</param>
        /// <returns><see langword="true"/> if a manual threat was found and removed; otherwise <see langword="false"/>.</returns>
        public static bool Remove(ThreatModel model, string threatId)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (string.IsNullOrWhiteSpace(threatId))
            {
                throw new ArgumentException("Value cannot be null or empty.", nameof(threatId));
            }

            foreach (KeyValuePair<string, Threat> pair in model.AllThreatsDictionary)
            {
                string interaction = string.IsNullOrEmpty(pair.Value.InteractionKey) ? pair.Key : pair.Value.InteractionKey!;
                bool manual = interaction.StartsWith("manual:", StringComparison.OrdinalIgnoreCase);
                bool matches =
                    string.Equals(pair.Key, threatId, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(interaction, threatId, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(pair.Value.Id.ToString(CultureInfo.InvariantCulture), threatId, StringComparison.Ordinal);
                if (matches)
                {
                    if (!manual)
                    {
                        return false;
                    }

                    model.AllThreatsDictionary.Remove(pair.Key);
                    return true;
                }
            }

            return false;
        }

        private static (Guid Source, Guid Target, Guid Flow) ResolveScope(IReadOnlyList<string>? elementIds)
        {
            Guid source = Guid.Empty;
            Guid target = Guid.Empty;
            Guid flow = Guid.Empty;
            if (elementIds != null)
            {
                if (elementIds.Count > 0)
                {
                    Guid.TryParse(elementIds[0], out source);
                }

                if (elementIds.Count > 1)
                {
                    Guid.TryParse(elementIds[1], out target);
                }

                if (elementIds.Count > 2)
                {
                    Guid.TryParse(elementIds[2], out flow);
                }
            }

            return (source, target, flow);
        }

        private static Guid FirstSurfaceGuid(ThreatModel model)
        {
            foreach (DrawingSurfaceModel surface in model.DrawingSurfaceList)
            {
                return surface.Guid;
            }

            return Guid.Empty;
        }

        private static RuleSet LoadDefaultRuleSet()
        {
            return AnalysisRuleSources.Create();
        }

        private static GeneratedThreat ToThreat(Message message, Rule rule, Entity target, StrideCategory category)
        {
            bool isFlow = target is Connector;
            Guid sourceGuid = target.Guid;
            Guid targetGuid = Guid.Empty;
            Guid flowGuid = Guid.Empty;
            string? sourceName = NameOf(target);
            string? targetName = null;
            string? flowName = null;
            string interactionString = sourceName ?? target.Guid.ToString();

            if (target is Connector connector)
            {
                sourceGuid = connector.SourceGuid;
                targetGuid = connector.TargetGuid;
                flowGuid = connector.Guid;
                flowName = NameOf(connector);
                sourceName = NameInDiagram(message.Model, connector.SourceGuid);
                targetName = NameInDiagram(message.Model, connector.TargetGuid);
                interactionString = (sourceName ?? "?") + " -> " + (targetName ?? "?");
            }

            return new GeneratedThreat
            {
                Id = string.Format(CultureInfo.InvariantCulture, "{0:N}:{1}", target.Guid, rule.ID),
                RuleId = rule.ID,
                Category = category,
                Title = message.Text ?? rule.FullDescription,
                Mitigation = string.IsNullOrWhiteSpace(rule.HelpText) ? null : rule.HelpText,
                Severity = rule.Severity.ToString().ToLowerInvariant(),
                Priority = PriorityFor(rule.Severity),
                References = rule.ThreatReferences,
                SourceGuid = sourceGuid,
                TargetGuid = targetGuid,
                FlowGuid = flowGuid,
                DiagramGuid = message.Model?.Guid ?? Guid.Empty,
                SourceName = sourceName,
                TargetName = targetName,
                FlowName = flowName,
                IsFlowScoped = isFlow,
                InteractionString = interactionString,
            };
        }

        private static Threat CreateThreat(GeneratedThreat threat, int id)
        {
            return new Threat
            {
                Id = id,
                TypeId = threat.RuleId,
                SourceGuid = threat.SourceGuid,
                TargetGuid = threat.TargetGuid,
                FlowGuid = threat.FlowGuid,
                DrawingSurfaceGuid = threat.DiagramGuid,
                State = ThreatState.AutoGenerated,
                InteractionKey = threat.Id,
                InteractionString = threat.InteractionString,
                Title = threat.Title,
                Priority = threat.Priority,
                UserThreatCategory = CategoryName(threat.Category),
                StateInformation = string.Empty,
                ModifiedAt = DateTime.UtcNow,
                Properties = BuildProperties(threat),
            };
        }

        private static void UpdateThreat(Threat existing, GeneratedThreat threat)
        {
            existing.TypeId = threat.RuleId;
            existing.SourceGuid = threat.SourceGuid;
            existing.TargetGuid = threat.TargetGuid;
            existing.FlowGuid = threat.FlowGuid;
            existing.DrawingSurfaceGuid = threat.DiagramGuid;
            existing.InteractionKey = threat.Id;
            existing.InteractionString = threat.InteractionString;
            existing.Title = threat.Title;
            existing.Priority = threat.Priority;
            existing.UserThreatCategory = CategoryName(threat.Category);
            existing.Properties = BuildProperties(threat);
            existing.ModifiedAt = DateTime.UtcNow;
        }

        private static Dictionary<string, string> BuildProperties(GeneratedThreat threat)
        {
            Dictionary<string, string> props = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Rule"] = threat.RuleId,
            };
            if (!string.IsNullOrWhiteSpace(threat.Mitigation))
            {
                props["Mitigation"] = threat.Mitigation!;
            }

            if (threat.References.Count > 0)
            {
                props["References"] = string.Join(", ", threat.References.Select(r => r.Id));
            }

            return props;
        }

        private static string PriorityFor(MessageSeverity severity)
        {
            switch (severity)
            {
                case MessageSeverity.Error:
                    return "High";
                case MessageSeverity.Info:
                    return "Low";
                default:
                    return "Medium";
            }
        }

        private static string CategoryName(StrideCategory category)
        {
            switch (category)
            {
                case StrideCategory.InformationDisclosure:
                    return "Information Disclosure";
                case StrideCategory.DenialOfService:
                    return "Denial of Service";
                case StrideCategory.ElevationOfPrivilege:
                    return "Elevation of Privilege";
                default:
                    return category.ToString();
            }
        }

        private static int NextThreatId(ThreatModel model)
        {
            int max = 0;
            foreach (Threat threat in model.AllThreatsDictionary.Values.Where(threat => threat.Id > max))
            {
                max = threat.Id;
            }

            return max + 1;
        }

        private static Threat? FindThreat(ThreatModel model, string threatId)
        {
            if (model.AllThreatsDictionary.TryGetValue(threatId, out Threat? byKey))
            {
                return byKey;
            }

            foreach (KeyValuePair<string, Threat> pair in model.AllThreatsDictionary)
            {
                if (string.Equals(pair.Value.InteractionKey, threatId, StringComparison.OrdinalIgnoreCase))
                {
                    return pair.Value;
                }

                if (string.Equals(pair.Value.Id.ToString(CultureInfo.InvariantCulture), threatId, StringComparison.Ordinal))
                {
                    return pair.Value;
                }
            }

            return null;
        }

        private static string? NameInDiagram(DrawingSurfaceModel? diagram, Guid id)
        {
            if (diagram != null && diagram.Borders.TryGetValue(id, out object? value) && value is Entity entity)
            {
                return NameOf(entity);
            }

            return null;
        }

        private static string? NameOf(Entity entity)
        {
            return entity.Name() ?? entity.HeaderName();
        }

        private static int CompareThreats(GeneratedThreat left, GeneratedThreat right)
        {
            int byCategory = left.Category.CompareTo(right.Category);
            if (byCategory != 0)
            {
                return byCategory;
            }

            int byRule = string.CompareOrdinal(left.RuleId, right.RuleId);
            if (byRule != 0)
            {
                return byRule;
            }

            return string.CompareOrdinal(left.Id, right.Id);
        }
    }
}
