namespace ThreatModelForge.KnowledgeBase
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    /// <summary>
    /// The workflow state of a threat instance. Two pairs of names share a value so files written by
    /// older tools deserialize correctly.
    /// </summary>
    public enum ThreatState
    {
        /// <summary>Auto-generated and not yet triaged.</summary>
        AutoGenerated = 0,

#pragma warning disable CA1069 // Enum values should not be duplicated; kept for backward-compatible deserialization.
        /// <summary>Legacy alias for the not-yet-triaged state.</summary>
        Migrated = 0,
#pragma warning restore CA1069 // Enum values should not be duplicated

        /// <summary>Marked not applicable.</summary>
        NotApplicable = 1,

        /// <summary>Needs investigation.</summary>
        NeedsInvestigation = 2,

#pragma warning disable CA1069 // Enum values should not be duplicated; kept for backward-compatible deserialization.
        /// <summary>Legacy alias for the needs-investigation state.</summary>
        NeedsMitigation = 2,
#pragma warning restore CA1069 // Enum values should not be duplicated

        /// <summary>Mitigation implemented.</summary>
        Mitigated = 3,
    }

    /// <summary>
    /// A single threat instance recorded against an interaction (data flow) in a model.
    /// </summary>
    [DataContract(
        Name = "Threat",
        Namespace = "http://schemas.datacontract.org/2004/07/ThreatModeling.KnowledgeBase")]
    public class Threat
    {
        /// <summary>Gets or sets the numeric identifier.</summary>
        [DataMember(Name = "Id")]
        public int Id { get; set; }

        /// <summary>Gets or sets the threat-type identifier.</summary>
        [DataMember(Name = "TypeId")]
        public string? TypeId { get; set; }

        /// <summary>Gets or sets the source element identifier.</summary>
        [DataMember(Name = "SourceGuid")]
        public Guid SourceGuid { get; set; }

        /// <summary>Gets or sets the target element identifier.</summary>
        [DataMember(Name = "TargetGuid")]
        public Guid TargetGuid { get; set; }

        /// <summary>Gets or sets the flow (connector) identifier.</summary>
        [DataMember(Name = "FlowGuid")]
        public Guid FlowGuid { get; set; }

        /// <summary>Gets or sets the diagram identifier.</summary>
        [DataMember(Name = "DrawingSurfaceGuid")]
        public Guid DrawingSurfaceGuid { get; set; }

        /// <summary>Gets or sets the workflow state.</summary>
        [DataMember(Name = "State")]
        public ThreatState State { get; set; }

        /// <summary>Gets or sets the interaction key identifying the flow.</summary>
        [DataMember(Name = "InteractionKey")]
        public string? InteractionKey { get; set; }

        /// <summary>Gets or sets the free-text state information / justification.</summary>
        [DataMember(Name = "StateInformation")]
        public string? StateInformation { get; set; }

        /// <summary>Gets or sets the user-assigned threat category.</summary>
        [DataMember(Name = "UserThreatCategory")]
        public string? UserThreatCategory { get; set; }

        /// <summary>Gets or sets the user-assigned short description.</summary>
        [DataMember(Name = "UserThreatShortDescription")]
        public string? UserThreatShortDescription { get; set; }

        /// <summary>Gets or sets the user-assigned description.</summary>
        [DataMember(Name = "UserThreatDescription")]
        public string? UserThreatDescription { get; set; }

        /// <summary>Gets or sets the human-readable interaction string.</summary>
        [DataMember(Name = "InteractionString")]
        public string? InteractionString { get; set; }

        /// <summary>Gets or sets the title.</summary>
        [DataMember(Name = "Title")]
        public string? Title { get; set; }

        /// <summary>Gets or sets the priority.</summary>
        [DataMember(Name = "Priority")]
        public string? Priority { get; set; }

        /// <summary>Gets or sets a value indicating whether this threat spans the whole model.</summary>
        [DataMember(Name = "Wide")]
        public bool Wide { get; set; }

        /// <summary>Gets or sets the identity that last changed this threat.</summary>
        [DataMember(Name = "ChangedBy")]
        public string? ChangedBy { get; set; }

        /// <summary>Gets or sets the last-modified timestamp.</summary>
        [DataMember(Name = "ModifiedAt")]
        public DateTime ModifiedAt { get; set; }

        /// <summary>Gets or sets a value indicating whether this threat was upgraded from an older schema.</summary>
        [DataMember(Name = "Upgraded")]
        public bool Upgraded { get; set; }

        /// <summary>Gets or sets the bag of extra properties.</summary>
        [DataMember(Name = "Properties")]
        public Dictionary<string, string>? Properties { get; set; }
    }
}
