namespace ThreatModelForge.Reporting.Tests
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using ThreatModelForge.KnowledgeBase;
    using ThreatModelForge.Model;
    using ThreatModelForge.Reporting;

    /// <summary>
    /// Unit tests for <see cref="HtmlReportWriter"/>.
    /// </summary>
    [TestClass]
    public class HtmlReportWriterTest
    {
        /// <summary>
        /// Verifies the report contains the metadata, the diagram SVG, and the threats.
        /// </summary>
        [TestMethod]
        public void WritesReportWithMetadataDiagramAndThreats()
        {
            string html = new HtmlReportWriter().Write(BuildModel("Spoofing of the web app"));

            StringAssert.StartsWith(html, "<!DOCTYPE html>");
            StringAssert.Contains(html, "Threat Modeling Report");
            StringAssert.Contains(html, "Test Model");
            StringAssert.Contains(html, "Main DFD");
            StringAssert.Contains(html, "Spoofing of the web app");
            StringAssert.Contains(html, "Needs Investigation");
            StringAssert.Contains(html, "<svg");
            StringAssert.Contains(html, "class=\"metrics\"");
            StringAssert.Contains(html, "class=\"threat-card threat-investigation\"");
            StringAssert.Contains(html, "--cp-accent");
            StringAssert.Contains(html, ".diagram-canvas .tmf-diagram");
            StringAssert.Contains(html, "<script>(function () {");
            Assert.IsFalse(html.Contains("=&gt;", StringComparison.Ordinal));
        }

        /// <summary>
        /// Verifies that user-supplied threat text is HTML-escaped, so a report cannot inject markup.
        /// </summary>
        [TestMethod]
        public void EscapesUserSuppliedText()
        {
            string html = new HtmlReportWriter().Write(BuildModel("<script>alert(1)</script>"));

            Assert.IsFalse(
                html.Contains("<script>alert(1)</script>", StringComparison.Ordinal),
                "user text must be HTML-escaped");
            StringAssert.Contains(html, "&lt;script&gt;");
        }

        /// <summary>
        /// A scoped threat is grouped with the diagram that owns its element even when legacy
        /// diagram metadata points at a different page.
        /// </summary>
        [TestMethod]
        public void GroupsThreatsByScopedElementPage()
        {
            DrawingSurfaceModel first = new DrawingSurfaceModel { Guid = Guid.NewGuid(), Header = "First page" };
            DrawingSurfaceModel second = new DrawingSurfaceModel { Guid = Guid.NewGuid(), Header = "Second page" };
            StencilRectangle component = new StencilRectangle { Guid = Guid.NewGuid(), TypeId = "GE.P" };
            component.Properties.Add(new StringDisplayAttribute { DisplayName = "Name", Value = "Second-page API" });
            second.Borders[component.Guid] = component;

            ThreatModel model = new ThreatModel();
            model.DrawingSurfaceList.Add(first);
            model.DrawingSurfaceList.Add(second);
            const string title = "Threat scoped to the second page";
            model.AllThreatsDictionary[Guid.NewGuid().ToString("N")] = new Threat
            {
                Title = title,
                SourceGuid = component.Guid,
                DrawingSurfaceGuid = first.Guid,
                State = ThreatState.AutoGenerated,
            };

            XDocument document = XDocument.Parse(new HtmlReportWriter().Write(model));
            List<XElement> sections = document.Descendants("section")
                .Where(element => ((string?)element.Attribute("class"))?.Contains("diagram-section", StringComparison.Ordinal) == true)
                .ToList();

            Assert.AreEqual(2, sections.Count);
            Assert.IsFalse(sections[0].Value.Contains(title, StringComparison.Ordinal));
            StringAssert.Contains(sections[1].Value, title);
            StringAssert.Contains(sections[1].Value, "Second-page API");
        }

        private static ThreatModel BuildModel(string threatTitle)
        {
            StencilRectangle rectangle = new StencilRectangle { Guid = Guid.NewGuid(), TypeId = "GE.P", Left = 0, Top = 0, Width = 80, Height = 40 };
            Connector flow = new Connector { Guid = Guid.NewGuid(), TypeId = "GE.DF", SourceX = 80, SourceY = 20, TargetX = 200, TargetY = 30 };
            DrawingSurfaceModel diagram = new DrawingSurfaceModel { Guid = Guid.NewGuid(), Header = "Main DFD" };
            diagram.Borders[rectangle.Guid] = rectangle;
            diagram.Lines[flow.Guid] = flow;

            ThreatModel model = new ThreatModel
            {
                MetaInformation = new MetaInformation { ThreatModelName = "Test Model", Owner = "graymark" },
            };
            model.DrawingSurfaceList.Add(diagram);

            Threat threat = new Threat
            {
                TypeId = "T1",
                Title = threatTitle,
                DrawingSurfaceGuid = diagram.Guid,
                State = ThreatState.NeedsInvestigation,
                Priority = "High",
                UserThreatDescription = "A spoofing threat.",
                StateInformation = "Enforce authentication.",
            };
            model.AllThreatsDictionary[Guid.NewGuid().ToString("N")] = threat;
            return model;
        }
    }
}
