namespace ThreatModelForge.Reporting.Tests
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Net;
    using System.Xml.Linq;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using ThreatModelForge.KnowledgeBase;
    using ThreatModelForge.Model;

    /// <summary>Tests the portable Markdown report contract.</summary>
    [TestClass]
    public class MarkdownReportWriterTest
    {
        /// <summary>Both report formats retain metadata, scoped threats, treatment and references.</summary>
        [TestMethod]
        public void MatchesHtmlThreatContent()
        {
            ThreatModel model = Model();
            string[] stale = { "generated:review" };
            string markdown = WebUtility.HtmlDecode(new MarkdownReportWriter().Write(model, stale));
            string html = XDocument.Parse(new HtmlReportWriter().Write(model, stale)).Root!.Value;

            foreach (string value in new[]
            {
                "Sample model", "Owner name", "Reviewer name", "Contributor name", "System description",
                "A recorded assumption", "An external dependency", "First page", "Second page",
                "Gateway", "Reviewed risk", "Tampering", "Needs Investigation", "High",
                "Detailed description", "Proposed mitigation", "CWE-287", "Decision rationale", "Stale",
            })
            {
                StringAssert.Contains(markdown, value);
                StringAssert.Contains(html, value);
            }

            StringAssert.Contains(markdown, "generated:review");
            Assert.AreEqual(1, markdown.Split("### Reviewed risk", StringSplitOptions.None).Length - 1);
            Assert.AreEqual(ThreatState.NeedsInvestigation, model.AllThreatsDictionary["generated:review"].State);
        }

        /// <summary>Model text remains literal in headings, list fields and tables.</summary>
        [TestMethod]
        public void EscapesMarkupAndNormalizesLineEndings()
        {
            ThreatModel model = Model();
            const string hostile = "[label](javascript:alert(1)) | <script>run()</script>\r\n# Heading\n`code` @team";
            model.MetaInformation!.ThreatModelName = hostile;
            model.AllThreatsDictionary["generated:review"].Title = hostile;

            string markdown = new MarkdownReportWriter().Write(model);

            Assert.IsFalse(markdown.Contains("<script>", StringComparison.Ordinal));
            Assert.IsFalse(markdown.Contains("[label]", StringComparison.Ordinal));
            Assert.IsFalse(markdown.Contains("javascript:", StringComparison.Ordinal));
            Assert.IsFalse(markdown.Contains("@team", StringComparison.Ordinal));
            Assert.IsFalse(markdown.Contains('\r'));
            StringAssert.Contains(markdown, "<br />&#35; Heading<br />&#96;code&#96;");
            StringAssert.Contains(WebUtility.HtmlDecode(markdown), hostile.Replace("\r\n", "<br />").Replace("\n", "<br />"));
        }

        /// <summary>Culture and dictionary insertion order do not change the report bytes.</summary>
        [TestMethod]
        public void IsIndependentOfCultureAndRegisterInsertionOrder()
        {
            ThreatModel model = Model();
            model.AllThreatsDictionary["manual:z"] = new Threat { Title = "Manual risk", State = ThreatState.NotApplicable };
            CultureInfo original = CultureInfo.CurrentCulture;
            try
            {
                CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("fr-FR");
                string first = new MarkdownReportWriter().Write(model);
                KeyValuePair<string, Threat>[] entries = model.AllThreatsDictionary.Reverse().ToArray();
                model.AllThreatsDictionary.Clear();
                foreach (KeyValuePair<string, Threat> entry in entries)
                {
                    model.AllThreatsDictionary.Add(entry.Key, entry.Value);
                }

                CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("tr-TR");
                Assert.AreEqual(first, new MarkdownReportWriter().Write(model));
            }
            finally
            {
                CultureInfo.CurrentCulture = original;
            }
        }

        /// <summary>Models without diagrams retain every status and unscoped manual decision.</summary>
        [TestMethod]
        public void WritesEveryStateWithoutDiagrams()
        {
            ThreatModel model = new ThreatModel();
            foreach (ThreatState state in new[] { ThreatState.AutoGenerated, ThreatState.NotApplicable, ThreatState.NeedsInvestigation, ThreatState.Mitigated })
            {
                model.AllThreatsDictionary["manual:" + state] = new Threat { Title = state.ToString(), State = state, StateInformation = "Retained" };
            }

            string markdown = new MarkdownReportWriter().Write(model);

            foreach (string label in new[] { "Open", "Accepted", "Needs Investigation", "Mitigated" })
            {
                StringAssert.Contains(markdown, "| " + label + " | 1 |");
            }

            StringAssert.Contains(markdown, "| Total | 4 |");
            StringAssert.Contains(markdown, "Manual entry");
            StringAssert.Contains(markdown, "Model-wide");
            StringAssert.Contains(markdown, "Retained");
        }

        /// <summary>Empty reports are explicit and a null input is rejected.</summary>
        [TestMethod]
        public void HandlesEmptyAndNullModels()
        {
            StringAssert.Contains(new MarkdownReportWriter().Write(new ThreatModel()), "No threats recorded.");
            Assert.Throws<ArgumentNullException>(() => new MarkdownReportWriter().Write(null!));
        }

        private static ThreatModel Model()
        {
            ThreatModel model = new ThreatModel
            {
                MetaInformation = new MetaInformation
                {
                    ThreatModelName = "Sample model", Owner = "Owner name", Reviewer = "Reviewer name",
                    Contributors = "Contributor name", HighLevelSystemDescription = "System description",
                    Assumptions = "A recorded assumption", ExternalDependencies = "An external dependency",
                },
            };
            DrawingSurfaceModel first = new DrawingSurfaceModel { Guid = Guid.NewGuid(), Header = "First page" };
            DrawingSurfaceModel second = new DrawingSurfaceModel { Guid = Guid.NewGuid(), Header = "Second page" };
            StencilEllipse gateway = new StencilEllipse { Guid = Guid.NewGuid(), GenericTypeId = "GE.P", TypeId = "GE.P", Width = 100, Height = 60 };
            gateway.Properties.Add(new StringDisplayAttribute { DisplayName = "Name", Value = string.Empty });
            gateway.Properties.Add(new StringDisplayAttribute { DisplayName = "Name", Value = "Gateway" });
            second.Borders[gateway.Guid] = gateway;
            model.DrawingSurfaceList.Add(first);
            model.DrawingSurfaceList.Add(second);
            model.AllThreatsDictionary["generated:review"] = new Threat
            {
                InteractionKey = "generated:review", TypeId = "TMTEST", Title = "Reviewed risk",
                State = ThreatState.NeedsInvestigation, Priority = "High", UserThreatCategory = "Tampering",
                UserThreatDescription = "Detailed description", StateInformation = "Decision rationale",
                SourceGuid = gateway.Guid, DrawingSurfaceGuid = first.Guid,
                Properties = new Dictionary<string, string>
                {
                    ["mitigation"] = string.Empty,
                    ["Mitigation"] = "Proposed mitigation",
                    ["REFERENCES"] = "CWE-287",
                },
            };
            return model;
        }
    }
}
