//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreatModelForge.Analysis.Rules.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreatModelForge.Analysis.Rules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up the localized EdgeMissingDataClassificationMessageText resource string.
        /// </summary>
        internal static string EdgeMissingDataClassificationMessageText {
            get {
                return ResourceManager.GetString("EdgeMissingDataClassificationMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized EdgeMissingPortInfoMessageText resource string.
        /// </summary>
        internal static string EdgeMissingPortInfoMessageText {
            get {
                return ResourceManager.GetString("EdgeMissingPortInfoMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized EdgeMissingProtocolDescriptionMessageText resource string.
        /// </summary>
        internal static string EdgeMissingProtocolDescriptionMessageText {
            get {
                return ResourceManager.GetString("EdgeMissingProtocolDescriptionMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized EdgeMissingProtocolInfoMessageText resource string.
        /// </summary>
        internal static string EdgeMissingProtocolInfoMessageText {
            get {
                return ResourceManager.GetString("EdgeMissingProtocolInfoMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized EdgeNamesShouldNotMatchEdgeTypeMessageText resource string.
        /// </summary>
        internal static string EdgeNamesShouldNotMatchEdgeTypeMessageText {
            get {
                return ResourceManager.GetString("EdgeNamesShouldNotMatchEdgeTypeMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized GeneralPurposeComponentNameShouldNotMatchTypeNameMessageText resource string.
        /// </summary>
        internal static string GeneralPurposeComponentNameShouldNotMatchTypeNameMessageText {
            get {
                return ResourceManager.GetString("GeneralPurposeComponentNameShouldNotMatchTypeNameMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized GenericComponentNameShouldNotMatchTypeNameMessageText resource string.
        /// </summary>
        internal static string GenericComponentNameShouldNotMatchTypeNameMessageText {
            get {
                return ResourceManager.GetString("GenericComponentNameShouldNotMatchTypeNameMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized MinimumComponentCountString resource string.
        /// </summary>
        internal static string MinimumComponentCountString {
            get {
                return ResourceManager.GetString("MinimumComponentCountString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized NoEdgeCrossesAnyTrustBoundaryInModel resource string.
        /// </summary>
        internal static string NoEdgeCrossesAnyTrustBoundaryInModel {
            get {
                return ResourceManager.GetString("NoEdgeCrossesAnyTrustBoundaryInModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized NoExternalInteractorDefinedInModel resource string.
        /// </summary>
        internal static string NoExternalInteractorDefinedInModel {
            get {
                return ResourceManager.GetString("NoExternalInteractorDefinedInModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized NoTrustBoundariesDefinedInModel resource string.
        /// </summary>
        internal static string NoTrustBoundariesDefinedInModel {
            get {
                return ResourceManager.GetString("NoTrustBoundariesDefinedInModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized StorageComponentMissingInboundEdgesMessageText resource string.
        /// </summary>
        internal static string StorageComponentMissingInboundEdgesMessageText {
            get {
                return ResourceManager.GetString("StorageComponentMissingInboundEdgesMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized UnconnectedComponentMessageText resource string.
        /// </summary>
        internal static string UnconnectedComponentMessageText {
            get {
                return ResourceManager.GetString("UnconnectedComponentMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized UnconnectedEdgeMissingSourceAndTargetMessageText resource string.
        /// </summary>
        internal static string UnconnectedEdgeMissingSourceAndTargetMessageText {
            get {
                return ResourceManager.GetString("UnconnectedEdgeMissingSourceAndTargetMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized UnconnectedEdgeMissingSourceMessageText resource string.
        /// </summary>
        internal static string UnconnectedEdgeMissingSourceMessageText {
            get {
                return ResourceManager.GetString("UnconnectedEdgeMissingSourceMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up the localized UnconnectedEdgeMissingTargetMessageText resource string.
        /// </summary>
        internal static string UnconnectedEdgeMissingTargetMessageText {
            get {
                return ResourceManager.GetString("UnconnectedEdgeMissingTargetMessageText", resourceCulture);
            }
        }
    }
}
