/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetFormats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stencils": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetStencils"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stencil-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetStencilPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rule-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRulePacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rule-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRuleBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/property-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPropertySchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnalyzeModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RunAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/analysis-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DescribeAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/threats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GenerateThreats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/threat-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DescribeThreatRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MergeModels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/export/tm7": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExportModelTm7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ConvertModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReadModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReportModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/analysis-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnalysisReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DetectFormat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalysisDocumentDto: {
            schema?: string;
            /** Format: int32 */
            version?: number | string;
            model?: components["schemas"]["AnalysisIdentityDto"];
            analyzer?: components["schemas"]["AnalysisIdentityDto"];
            rulePacks?: components["schemas"]["RulePackInfoDto"][];
            findings?: components["schemas"]["AnalysisFindingDto"][];
            diagnostics?: string[];
        };
        AnalysisFindingDto: {
            id?: string;
            ruleId?: string;
            severity?: string;
            message?: string;
            diagram?: null | string;
            elementIds?: string[];
            disposition?: string;
            threatId?: null | string;
            canonicalIds?: string[];
        };
        AnalysisIdentityDto: {
            name?: string;
            version?: null | string;
            fingerprint?: string;
        };
        AnalysisResultDto: {
            findings?: components["schemas"]["FindingDto"][];
            threats?: components["schemas"]["ThreatDto"][];
            rulePacks?: components["schemas"]["RulePackInfoDto"][];
            diagnostics?: string[];
        };
        ExpectedRulePackDto: {
            id?: null | string;
            fingerprint?: null | string;
        };
        FileContentDto: {
            contentBase64?: string;
            formatId?: null | string;
        };
        FindingDto: {
            id?: string;
            severity?: string;
            ruleId?: null | string;
            message?: string;
            elementIds?: string[];
        };
        FormatDto: {
            id?: string;
            displayName?: string;
            extensions?: string[];
            canRead?: boolean;
            canWrite?: boolean;
        };
        HealthStatusDto: {
            status?: string;
        };
        MergeConflictDto: {
            elementId?: null | string;
            elementKind?: null | string;
            name?: null | string;
            diagramName?: null | string;
            kind?: null | string;
            property?: null | string;
            base?: null | string;
            ours?: null | string;
            theirs?: null | string;
        };
        MergeRequestDto: {
            base?: null | components["schemas"]["TmForgeModelDto"];
            ours?: null | components["schemas"]["TmForgeModelDto"];
            theirs?: null | components["schemas"]["TmForgeModelDto"];
        };
        MergeResultDto: {
            merged?: null | components["schemas"]["TmForgeModelDto"];
            conflicts?: null | components["schemas"]["MergeConflictDto"][];
        };
        /**
         * @description Describes a stencil pack: a named, togglable group of related stencils (for example, the
         *     Azure pack). The palette uses packs so the user can show or hide whole families at once.
         */
        PackDto: {
            /** @description Gets the stable pack identifier (for example, `azure`). */
            id?: string;
            /** @description Gets the human-readable pack name shown in the palette. */
            name?: string;
            /**
             * Format: int32
             * @description Gets the number of stencils the pack contributes.
             */
            count?: number | string;
        };
        /**
         * @description Typed definition of a single element custom property (for example, a data store's
         *     `Encrypted` setting). The schema lets authoring surfaces render the right control
         *     (dropdown, checkbox, or free text) and emit canonical values, so the analysis rules that
         *     inspect these properties match reliably instead of guessing at free-form text.
         */
        PropertyDescriptor: {
            /** @description Gets the DFD primitive this property applies to (`process`, `datastore`, `external`, or `flow`). */
            appliesTo?: string;
            /** @description Gets the property name, i.e. the custom-attribute key (for example, `AuthenticationScheme`). */
            name?: string;
            /** @description Gets the value kind that drives the editor control: `enum`, `bool`, or `string`. */
            kind?: string;
            /** @description Gets the allowed values for an `enum` or `bool` property; empty for a free-form `string`. */
            values?: string[];
            /** @description Gets the default value applied when the property is first added to an element. */
            default?: string;
        };
        RuleBundleDto: {
            rulePacks?: components["schemas"]["RulePackInfoDto"][];
            diagnostics?: string[];
        };
        RuleDto: {
            id?: string;
            pack?: string;
            severity?: string;
            description?: string;
            helpText?: string;
            helpUri?: null | string;
        };
        RulePackDto: {
            id?: string;
            name?: string;
            /** Format: int32 */
            count?: number | string;
        };
        RulePackInfoDto: {
            id?: string;
            name?: string;
            version?: null | string;
            fingerprint?: string;
            dialect?: string;
            /** Format: int32 */
            ruleCount?: number | string;
        };
        /**
         * @description Describes an authoring stencil: a named, categorized specialization of one of the four DFD
         *     primitives (`process`, `datastore`, `external`, `boundary`). A stencil
         *     maps to its string StencilDto.Base primitive for analysis, and its identity plus preset
         *     properties enrich the model without requiring per-stencil rules.
         */
        StencilDto: {
            /** @description Gets the stable stencil identifier (for example, `azure-sql`). */
            id?: string;
            /** @description Gets the underlying DFD primitive this stencil maps to. */
            base?: string;
            /** @description Gets the human-readable name shown in the palette. */
            label?: string;
            /** @description Gets the palette grouping this stencil belongs to. */
            category?: string;
            /** @description Gets the stencil pack this stencil ships in (for example, `azure`). */
            pack?: string;
            /** @description Gets a short description of the stencil. */
            blurb?: string;
            /** @description Gets the free-form search tags and aliases for this stencil. */
            tags?: string[];
            /** @description Gets the preset custom properties applied when the stencil is placed. */
            defaults?: {
                [key: string]: string;
            };
        };
        ThreatDto: {
            id?: string;
            ruleId?: string;
            category?: string;
            categoryId?: null | string;
            categoryName?: null | string;
            stride?: null | string;
            title?: string;
            mitigation?: null | string;
            severity?: string;
            priority?: null | string;
            references?: string[];
            elementIds?: string[];
            interaction?: string;
            state?: string;
            justification?: null | string;
            description?: null | string;
            manual?: boolean;
        };
        ThreatRegisterDto: {
            /** Format: int32 */
            manual?: number | string;
            /** Format: int32 */
            persistedGenerated?: number | string;
            /** Format: int32 */
            currentGenerated?: number | string;
            /** Format: int32 */
            staleGenerated?: number | string;
            /** Format: int32 */
            indeterminateGenerated?: number | string;
            unavailableRuleIds?: string[];
            entries?: components["schemas"]["ThreatRegisterEntryDto"][];
            diagnostics?: string[];
            rulePacks?: components["schemas"]["RulePackInfoDto"][];
        };
        ThreatRegisterEntryDto: {
            id?: string;
            state?: string;
            ruleId?: null | string;
            title?: string;
            triage?: string;
            hasTriage?: boolean;
        };
        ThreatStateDto: {
            id?: string;
            state?: string;
            justification?: null | string;
            manual?: null | boolean;
            category?: null | string;
            title?: null | string;
            description?: null | string;
            mitigation?: null | string;
            priority?: null | string;
            elementIds?: null | string[];
        };
        TmForgeAnalysisDto: {
            disabledPacks?: null | string[];
            disabledRuleIds?: null | string[];
            expectedPacks?: null | components["schemas"]["ExpectedRulePackDto"][];
        };
        TmForgeDiagramDto: {
            id?: string;
            name?: string;
            elements?: null | components["schemas"]["TmForgeElementDto"][];
            flows?: null | components["schemas"]["TmForgeFlowDto"][];
        };
        TmForgeElementDto: {
            id?: string;
            kind?: string;
            name?: null | string;
            /** Format: int32 */
            x?: number | string;
            /** Format: int32 */
            y?: number | string;
            /** Format: int32 */
            width?: null | number | string;
            /** Format: int32 */
            height?: null | number | string;
            properties?: {
                [key: string]: string;
            };
        };
        TmForgeFlowDto: {
            id?: string;
            source?: string;
            target?: string;
            name?: null | string;
            properties?: {
                [key: string]: string;
            };
        };
        TmForgeModelDto: {
            schema?: null | string;
            version?: null | string;
            elements?: null | components["schemas"]["TmForgeElementDto"][];
            flows?: null | components["schemas"]["TmForgeFlowDto"][];
            diagrams?: null | components["schemas"]["TmForgeDiagramDto"][];
            analysis?: null | components["schemas"]["TmForgeAnalysisDto"];
            threats?: null | components["schemas"]["ThreatStateDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatusDto"];
                };
            };
        };
    };
    GetFormats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormatDto"][];
                };
            };
        };
    };
    GetStencils: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StencilDto"][];
                };
            };
        };
    };
    GetStencilPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackDto"][];
                };
            };
        };
    };
    GetRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDto"][];
                };
            };
        };
    };
    GetRulePacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackDto"][];
                };
            };
        };
    };
    GetRuleBundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleBundleDto"];
                };
            };
        };
    };
    GetPropertySchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDescriptor"][];
                };
            };
        };
    };
    AnalyzeModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDto"][];
                };
            };
        };
    };
    RunAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResultDto"];
                };
            };
        };
    };
    DescribeAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDocumentDto"];
                };
            };
        };
    };
    GenerateThreats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreatDto"][];
                };
            };
        };
    };
    DescribeThreatRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreatRegisterDto"];
                };
            };
        };
    };
    MergeModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeResultDto"];
                };
            };
        };
    };
    ExportModelTm7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConvertModel: {
        parameters: {
            query: {
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReadModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileContentDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TmForgeModelDto"];
                };
            };
        };
    };
    ReportModel: {
        parameters: {
            query: {
                format: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalysisReport: {
        parameters: {
            query: {
                format: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmForgeModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DetectFormat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileContentDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormatDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
