//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreatModelForge.Analysis.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EdgeMissingProtocolRuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EdgeMissingProtocolRuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreatModelForge.Analysis.Rules.EdgeMissingProtocolRuleResources", typeof(EdgeMissingProtocolRuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges need to specify which protocol they use to describe the system. The protocol is examined during threat analysis to ensure protections are in place to secure the connection and analyze known input validation or other weaknesses in the protocol..
        /// </summary>
        internal static string FullDescription {
            get {
                return ResourceManager.GetString("FullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule is satisfied if one of the following conditions are met:
        ///1. The type of stencil used matches a well known protocol. Ex. &quot;HTTP&quot; or &quot;HTTPS&quot;.
        ///2. The edge has a custom attribute specifying the protocol in the &quot;Protocol:&lt;name&gt;&quot; format.
        ///3. The edge has text in its description specifying the protocol in the &quot;Protocol:&lt;name&gt;&quot; or &quot;Protocol=&lt;name&gt;&quot; format.
        ///4. The edge has text in its description matching the name of a well-known protocol. Ex. &quot;HTTP&quot;..
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
    }
}
