//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreatModelForge.Analysis.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EdgeMissingDataClassificationRuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EdgeMissingDataClassificationRuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreatModelForge.Analysis.Rules.EdgeMissingDataClassificationRuleRes" +
                            "ources", typeof(EdgeMissingDataClassificationRuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges should describe the data type (data classification tag) used. While more relevant to a privacy review, this information also helps a reviewer understand and suggest what kinds of protections and access models should be used with the data. By default, the rule is pre-populated with the set of known data classification tags, ex. EUII, EUPI, System Metadata, etc... This list can be customized in the build and individual edges can specify custom tags as well. To avoid having to specify the same text repea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullDescription {
            get {
                return ResourceManager.GetString("FullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule is satisfied if one of the following conditions is met:
        ///1. The edge has a custom attribute of the format &quot;DataType:&lt;value&gt;&quot;. Ex. &quot;DataType:EUPI&quot;.
        ///2. The edge description has text to explicitly specify the data type in the format &quot;DataType=&lt;value&gt;&quot; or &quot;DataType:&lt;value&gt;&quot; where &lt;value&gt; could be one word or multiple words enclosed in parathesis. Ex. &quot;DataType=EUPI&quot; or &quot;DataType=(System Metadata)&quot;.
        ///3. The edge description has text containing one or more of the configured classification tags, ex. EUII [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
    }
}
